### ISSUE TITLE
Throw exception when access fbo.color_attachments

### ISSUE THREAD

**Issue by xiongyaohua** [cprogrammer1994/ModernGL#103]
### Expected behavior

print a list of color attachments.

### Actual behavior

throw an exception.

### Steps to reproduce behavior

running following code
```python
import ModernGL as mgl
size = (256, 256)
ctx = mgl.create_standalone_context(size)
color_rbo = ctx.renderbuffer(size)
depth_rbo = ctx.depth_renderbuffer(size)
fbo = ctx.framebuffer(color_rbo, depth_rbo)
print(fbo.depth_attachment)
print(mgl.__version__)
print(fbo.color_attachments)
```

### Version info

```
python -m ModernGL
```
4.1.7
```
Paste the output here.
```
<Renderbuffer: 2>
4.1.7
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print(fbo.color_attachments)
  File "/usr/lib/python3.6/site-packages/ModernGL/renderbuffers.py", line 39, in __repr__
    return '<Renderbuffer: %d>' % self.glo
  File "/usr/lib/python3.6/site-packages/ModernGL/renderbuffers.py", line 96, in glo
    return self.mglo.glo
AttributeError: 'generator' object has no attribute 'glo'
```

**Comment by cprogrammer1994** [comment]
Thank you for pointing it out!

You can check the changes before a new release by installing ModernGL from the github.

```
python -m pip install ModernGL git+https://github.com/cprogrammer1994/ModernGL
```

**Comment by xiongyaohua** [comment]
Thank you for the tip and the awesome work^_^
