### ISSUE TITLE
Index buffer example

### ISSUE THREAD

**Issue by Korijn** [cprogrammer1994/ModernGL#116]
It took me quite some time to find examples of VAO with index buffer.

https://github.com/cprogrammer1994/ModernGL/blob/2f05ffb74ffc23bb798d2e550845ccccca2312f8/examples/PyQt5/untitled.py

This seems to be the only case where there is some advanced VAO usage. You should highlight it in the docs, it is a great example!

**Comment by cprogrammer1994** [comment]
Yes you are right. I will add a few examples with indexing

**Comment by cprogrammer1994** [comment]
I've added 2 examples. Maybe I should reconsider the numbering of the examples.
- [06_index_buffer](https://github.com/cprogrammer1994/ModernGL/blob/master/examples/GLWindow/06_index_buffer.py)
- [07_multiple_vertex_buffers](https://github.com/cprogrammer1994/ModernGL/blob/master/examples/GLWindow/07_multiple_vertex_buffers.py)

If you have index buffer examples as well please share 😄

**Comment by Korijn** [comment]
Working on it. :)

**Comment by Korijn** [comment]
My codebase has some abstractions on top so it is not immediately clear how it will be a useful example for your library. So I dont think I will be able to comply with what I said earlier. Thanks for the help though, your library is really nice!

**Comment by RenaKunisaki** [comment]
These links are broken.

**Comment by einarf** [comment]
@RenaKunisaki https://github.com/moderngl/moderngl/tree/master/examples
