### ISSUE TITLE
Multiple Textures in a shader

### ISSUE THREAD

**Issue by richIsBored** [cprogrammer1994/ModernGL#117]
I'm passing multiple textures to a fragment shader. I've verified that each texture loads correctly and each texture is bound to a different location. Adding both samplers together in the fragment shader does not yield the expected result. Instead of two different textures I see the same image superimposed on top of itself. I'm assuming it's something I'm doing wrong but there are no examples to draw from.

**main.py**
```
# Native Modules
import struct
import tkinter as tk

# External Modules
from lib import ModernGL
from lib.ModernGL import tk as ModernGL_tk
from lib.PIL import Image

ctx = ModernGL.create_standalone_context()

fbo = ctx.framebuffer(ctx.renderbuffer((512, 512)))

with open('shader/default_vertex.glsl') as f:
	v_sdr = f.read()

with open('shader/lut.glsl') as f:
	f_sdr = f.read()

prog = ctx.program([
	ctx.vertex_shader(v_sdr),
	ctx.fragment_shader(f_sdr),
	])

img1 = Image.open('texture/shady-forest.jpg')
texture1 = ctx.texture(img1.size, 3, img1.tobytes())
texture1.use(prog.uniforms['img'].location)

img2 = Image.open('texture/test_clut.ppm')
texture2 = ctx.texture(img2.size, 3, img2.tobytes())
texture2.use(prog.uniforms['clut'].location)

vbo = ctx.buffer(struct.pack('16f', -1.0, -1.0, 0.0, 0.0,
									-1.0, 1.0, 0.0, 1.0,
									1.0, -1.0, 1.0, 0.0,
									1.0, 1.0, 1.0, 1.0))
vao = ctx.simple_vertex_array(prog, vbo, ['vert', 'tex_coord'])

root = tk.Tk()
frame = ModernGL_tk.ModernGLCanvas(root, 512, 512)
frame.pack()

def draw():

	fbo.use()
	fbo.clear(0.94, 0.94, 0.94)
	vao.render(ModernGL.TRIANGLE_STRIP)

	fbo.read_into(frame.pixels)
	frame.update()
	frame.after(16, draw)

frame.after(16, draw)

root.mainloop()
```

**shader/default_vertex.glsl**
```
#version 330

in vec2 vert;
in vec2 tex_coord;
out vec2 v_tex_coord;

void main() {
	gl_Position = vec4(vert, 0.0, 1.0);
	v_tex_coord = tex_coord;
}
```

**shader/lut.glsl**
```
#version 330

uniform sampler2D img;
uniform sampler2D clut;

in vec2 v_tex_coord;
out vec4 color;

void main()
{
	color = texture(img, v_tex_coord) + texture(clut, v_tex_coord);
}
```

**Comment by cprogrammer1994** [comment]
By default all the textures are bound to `GL_TEXTURE0`

I assume

```python
print(prog.uniforms['img'].location) # prints 0
print(prog.uniforms['clut'].location) # prints 0
```

```python
prog.uniforms['img'].location = 0
prog.uniforms['clut'].location = 1

texture1.use(0)
texture2.use(1)
```

**Comment by cprogrammer1994** [comment]
your code will work if the `lut.glsl` uses `layout(binding = ...) uniform sampler2D ...;` for the uniforms. ( you will need 2 different binding points )

[Layout_Qualifier_(GLSL)](https://www.khronos.org/opengl/wiki/Layout_Qualifier_(GLSL))

> I prefer setting those values from the code

**Comment by cprogrammer1994** [comment]
I just noticed that you use the uniform location (`prog.uniforms['img'].location`)
You should use the value instead (`prog.uniforms['img'].value`)

The uniforms have different location (since they are 2 different uniforms) but they refference the same texture since their values are equal to 0.

**Comment by richIsBored** [comment]
```
prog.uniforms['img'].value = 0
prog.uniforms['clut'].value = 1

texture1.use(0)
texture2.use(1)
```

This solves the problem. Thanks for the direction.

**Comment by cprogrammer1994** [comment]
Take a look at this [new example](https://github.com/cprogrammer1994/heightmap-multitexture-terrain) I hope it will help.

**Comment by cprogrammer1994** [comment]
I will highlight the difference in the docs. Thank you for reporting this issue.
