### ISSUE TITLE
Parameters for Face Culling

### ISSUE THREAD

**Issue by cprogrammer1994** [cprogrammer1994/ModernGL#119]
### Expected behavior

Add support to `glCullFace` or `glFrontFace`

1. [glCullFace](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glCullFace.xhtml)
2. [glFrontFace](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glFrontFace.xhtml)

### Actual behavior

Not yet implemented.

**Comment by cprogrammer1994** [comment]
The method is often called "Backface Culling" so maybe it is better to use `glFrontFace` to specify weather `GL_CW` or `GL_CCW` is the Backface.

### Implementation 1

```python
ctx.front_face = ModernGL.CW
ctx.front_face = ModernGL.CCW
```

### Implementation 2

```python
ctx.back_face = ModernGL.CW
ctx.back_face = ModernGL.CCW
```

### Implementation 3

```python
ctx.cull_face = ModernGL.FRONT_FACE
ctx.cull_face = ModernGL.BACK_FACE
ctx.cull_face = ModernGL.FRONT_AND_BACK_FACE    # advantages of this?
```

---

I find the *Implementation 2* the most appropiate. The culling will be called backface culling and the backface can be changed to either CW or CCW.

**Comment by cprogrammer1994** [comment]
[Face_Culling](https://www.khronos.org/opengl/wiki/Face_Culling)

**Comment by cprogrammer1994** [comment]
Added in 4.1.11

**Comment by fekga** [comment]
Setting the winding order is not allowing the actual face culling to be made.
Winding order refers to the order of vertices sent to the primitive assembly which determines if that triangle is front or backfacing.
Culling will discard front/back/both triangles (only triangles and not other primitives) before rasterization.
For these reasons the face culling should be added as it is in the Implementation 3.
Also it needs to be en/disabled via glEnable/glDisable(GL_CULL_FACE) then be used with glCullFace(GL_FRONT/GL_BACK/GL_FRONT_AND_BACK).

The winding order can still remain as it is a different feature.

**Comment by einarf** [comment]
@fekga Maybe better to make a new issue and link to this one if there is an issue with the current implementation.
