### ISSUE TITLE
Python 2.7.13 - Windows install not working?

### ISSUE THREAD

**Issue by wangsen1312** [cprogrammer1994/ModernGL#127]
How to install ModernGL to windows?
It seems that the pip install is not working for this. (I use python 2.7.13)

**Comment by cprogrammer1994** [comment]
ModernGL is not working with Python 2.7.x since the type hinting was added. I am willing to restore the compatibility as far as I can keep the linting. (The type hints are really useful when using pylint from vscode)

I recommend to use ModernGL with Python 3 (wheel files are provided for windows, mac and linux too)

**Comment by cprogrammer1994** [comment]
Another problem with Python 2 on windows is that the [compiler](https://wiki.python.org/moin/WindowsCompilers) required for Python 2.7 is not installing properly on any of my computers. The official download link is [here](https://www.microsoft.com/en-us/download/details.aspx?id=44266).

**Comment by wangsen1312** [comment]
@cprogrammer1994  Thank you very much! I will test 2.7 version first since all my code are under 2.7.

**Comment by cprogrammer1994** [comment]
The following parts block the python 2 compatibility:

- `Foobar.__new__(...)` is used for each class in the python layer
- Keyword arguments were forced with a special `, *,` argument.
- I achieved to compile the C++ layer with g++ but I think the operations involving Unicode objects will not work properly with python 2.

Feel free to fork the repo and implement the necessary parts.

I run a few regex replaces:

- replace `->[^:]+:` with `:` in the python files
- replace `, \*,` with `,` in the python files

The rest must be done manually I guess. I achieved to install the module but The `__new__` method is not recognized. Too many parts need to be changed to support python 2.

Hint: You could try to use [py-backwards](https://github.com/nvbn/py-backwards) on the python layer.

**Comment by cprogrammer1994** [comment]
Using py-backwards on ModernGL depends on https://github.com/nvbn/py-backwards/issues/37
