### ISSUE TITLE
Uniform value can not be updated on my linux platform.

### ISSUE THREAD

**Issue by xndcn** [cprogrammer1994/ModernGL#128]
python -m ModernGL
> ModernGL: 4.1.11
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Haswell Desktop 
Version: 3.3 (Core Profile) Mesa 10.1.3
Python: 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Platform: linux

After I set uniform value by `foo.value = bar`, the `foo.value` is not updated...
But I try to replace `gl.ProgramUniform` by `gl.Uniform`, then it works well.
So I think `gl.ProgramUniform` may not supported well on some devices...

I'm not familiar with ModernGL, but I do upload my commit here, and it works well on my computer:
https://github.com/xndcn/ModernGL/commit/46e8f8edb3352b3f81dbcf57f42656d22a9888d5

**Comment by cprogrammer1994** [comment]
Thanks for the feedback! `glProgramUniform` is core in OpenGL 4.1

1. Can you please verify if `gl.ProgramUniform` is `NULL`?
2. Please run the following code:

```python
foo.value = bar    # foo is a uniform
print(ctx.error)   # ctx is a ModernGL context
```

This would help me a lot since I am not able to reproduce the problem.

It is likely that I will add an implementation for `gl.ProgramUniform` to call `gl.UseProgram` + `gl.Uniform` when `gl.ProgramUniform` is `NULL`

**Comment by cprogrammer1994** [comment]
I found the solution for **1.**

In your fork you have the checks [here](https://github.com/xndcn/ModernGL/blob/46e8f8edb3352b3f81dbcf57f42656d22a9888d5/src/GLMethods.cpp#L1068).
Since they pass I assume you have `glProgramUniform` supported.

I will try to install `Mesa 10.1.3` to see if I can reproduce the problem.

**Comment by cprogrammer1994** [comment]
```
Linux ubuntu-512mb-fra1-01 3.13.0-121-generic #170-Ubuntu SMP Wed Jun 14 09:05:46 UTC 2017 i686 i686 i686 GNU/Linux
```

```
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.4, 256 bits)
OpenGL version string: 2.1 Mesa 10.1.3
OpenGL shading language version string: 1.30
OpenGL extensions:
```

Lack of OpenGL support using mesa `Mesa 10.1.3`

**Comment by gauravssnl** [comment]
When I run ModernGL's   GLUT ,pygame,Kivy examples ,i get this error as shown in screenshot 

0:2(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

What is the solution fot this ??? @cprogrammer1994 
![screenshot from 2017-07-18 21-32-40](https://user-images.githubusercontent.com/13808299/28379393-17596a4e-6cd1-11e7-96e5-cfa883f52cef.png)

**Comment by cprogrammer1994** [comment]
@gauravssnl 

> OpenGL ES 3.2 works mostly on the same hardware as OpenGL 3.1

ModernGL requires OpenGL 3.3 at least. However it may work if you replace the shaders (not just the `#version 330` but make them compatible with [glsl 1.5](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.1.50.pdf) or older)

Is your hardware old? If not you may need to upgrade your drivers. (with the latest Mesa driver you can have OpenGL 3.3 support from software)

**Comment by gauravssnl** [comment]
Actually,my hardware is not old.AMD drivers  do not work on Ubuntu 16.04 ,so I have to use Intel Drivers.
My OpenGL details and Graphics card details are shown in screnshot.My system has 2GB AMD graphics card.As,there is no driver support ,i am using updated Intel drivers and I updated OPenGL from https://download.01.org/gfx/ubuntu/16.04/main 
I use this tool to update drivers : https://01.org/linuxgraphics/downloads/intel-graphics-update-tool-linux-os-v2.0.2
Just have a look at my config details ,please. @cprogrammer1994 

![screenshot from 2017-07-19 23-45-30](https://user-images.githubusercontent.com/13808299/28382668-9cc5d1a8-6cdc-11e7-835f-6002264046db.png)

**Comment by xndcn** [comment]
@cprogrammer1994 Thanks!
1. `gl.ProgramUniform` is not `NULL`
2. `print(ctx.error)` outputs `GL_INVALID_OPERATION` every time.

So I think it may be just a bug in `Mesa` or Intel graphic driver.

**Comment by cprogrammer1994** [comment]
@xndcn 
It is possible that `GL_INVALID_OPERATION` is generated. ([list of possible errors](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glProgramUniform.xhtml#errors))

Can you please paste the GLSL source code of the shader?

Please check the error before and after the uniform setter to make sure that the error is generated in the `glProgramUniform` call.

You can find some information about the [ModernGL Uniform](https://moderngl.readthedocs.io/en/stable/Uniforms.html).

```python
print(foobar.name)
print(foobar.location)
print(foobar.dimension)
print(foobar.array_length)

print(ctx.error)      # This will clear the error
print(foobar.value)
print(ctx.error)      # This will show the error generated by the value getter
foobar.value = ...
print(ctx.error)      # This will show the error generated by the value getter
```

**Comment by cprogrammer1994** [comment]
@gauravssnl I had a Radeon HD 5650. I was able to install the drivers from AMD's website. I was not able to install it with apt.

[BinaryDriverHowto](https://help.ubuntu.com/community/BinaryDriverHowto/AMD)

I think your HW supports OpenGL 4.5 but the driver is not properly installed.
(the glxinfo OpenGL core profile version string may come from the HW but the OpenGL shading language version string is 1.30 so you driver have no OpenGL 3.3 support)

**Comment by gauravssnl** [comment]
@cprogrammer1994  I had downloaded AMDGPU-PRO from their website as it is stated that it supports Ubuntu 16.04 but whenever i install the drivers,my screen goes blank .and i have to uninstall it by booting into recovery mode and then uninstall the drivers.
For Ubuntu 16.04 LTS and above, the AMD Catalyst or fglrx driver is no longer supported by AMD,.My  Graphics card is AMD Radeon R5 M430

**Comment by xndcn** [comment]
@cprogrammer1994 I only used two uniform so I think it should not hit the limit.
Besides, when I replace `glProgramUniform*` by `glUniform*`, the same code works well.

# error generated in the glProgramUniform call
print(ctx.error)      # GL_NO_ERROR
print(foobar.value)
print(ctx.error)      # GL_NO_ERROR
foobar.value = ...
print(ctx.error)      # GL_INVALID_OPERATION

**Comment by cprogrammer1994** [comment]
@gauravssnl did you manage to download a better driver?
@xndcn is there anything I can help?

**Comment by gauravssnl** [comment]
@cprogrammer1994  I am sorry ,I did not manage to install a better driver.I was busy in university exams.

**Comment by xndcn** [comment]
@cprogrammer1994 Thanks, I think it must be bugs in graphic driver, so please forget it.
