### ISSUE TITLE
pygame examples are not working anymore

### ISSUE THREAD

**Issue by Mano-Wii** [cprogrammer1994/ModernGL#134]
### Actual behavior

```
Traceback (most recent call last):
  File "C:\Germano\Dev\Gartic\tests\tests2.py", line 4, in <module>
    import pygame
  File "C:\Germano\Dev\Gartic\tests\pygame.py", line 35, in <module>
    ctx = ModernGL.create_context()
  File "C:\Users\Germano\AppData\Local\Programs\Python\Python36\lib\site-packages\ModernGL\context.py", line 730, in create_context
    ctx = Context.new(mgl.create_context())
mgl.Error: cannot detect context
>>> 
```

### Steps to reproduce behavior

I updated PyOpenGL to 3.1.1 and now ModernGL no longer works :(

### Version info

```
ModernGL: 4.1.11
Vendor: Intel
Renderer: Intel(R) HD Graphics 4000
Version: 4.0.0 - Build 10.18.10.4358
Python: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
Platform: win32
```

**Comment by cprogrammer1994** [comment]
Is the window created before the ModernGL context?
Is there a valid OpenGL context after pygame is initialized? (Do you set the proper flags?)

Your file is called pygame just like the module. Can it cause any unwanted behaviour?

**Comment by cprogrammer1994** [comment]
ModernGL does not depend on PyOpenGL. There must be some other issues.

**Comment by Mano-Wii** [comment]
> Is the window created before the ModernGL context?

I do not know (if it does not have thread delay then yes): I basically ran the "hello_word" templage of pygame. I copied the contents into a file called test.py

**Comment by Mano-Wii** [comment]
Actually was a big and stupid mistake mine!! Sorry. Forget everything.
