### ISSUE TITLE
Example of multiple textures

### ISSUE THREAD

**Issue by Korijn** [cprogrammer1994/ModernGL#135]
For example when I want to use a texture map and a normal map for a single program, how does ModernGL decide which `Sampler2D` corresponds to which `texture.use()` call? Is there an example of multiple texture use?

**Comment by cprogrammer1994** [comment]
`texture.use()` is equal to `texture.use(0)`. `0` stands for `GL_TEXTURE0`

Here is a small snippet to show how to assign textures to samplers easily:

```py
texture1.use(1)
texture2.use(2)
texture3.use(3)

program.uniforms['sampler1'].value = 1
program.uniforms['sampler2'].value = 2
program.uniforms['sampler3'].value = 3
```

I will add an example and I will link it in the docs.

This is a small project that uses multiple textures: [heightmap-multitexture-terrain](https://github.com/cprogrammer1994/heightmap-multitexture-terrain)

> PS: I am currently unifying the examples (a single example file will work with multiple window implementations).

Thank you for the feedback!

**Comment by cprogrammer1994** [comment]
Hello!

I refactored the examples and added an example for multi textures.
If you want to run the examples please install the following modules first:

```
pip install ModernGL ModernGL.ext.examples ModernGL.ext.obj
```

The multi texture example is: [examples/multi_texture_terrain.py](https://github.com/cprogrammer1994/ModernGL/blob/master/examples/multi_texture_terrain.py)

**Comment by Korijn** [comment]
Awesome, thanks! I'm currently working on something else but radiant will become a priority for me again in a month or so.

**Comment by einarf** [comment]
Taking the liberty of closing this issue. The multitexture example is present and some of the comments here may even refer to version 4.x.
