### ISSUE TITLE
KeyError with unused uniform

### ISSUE THREAD

**Issue by fekga** [cprogrammer1994/ModernGL#149]
### Expected behavior

Reaching an unused uniform should not be a problem. By unused uniform I mean that it appears as a uniform at the top of the shader but there is no read/write operation in the shader using it.

### Actual behavior

It raises a KeyError when I want to name the uniform.

### Steps to reproduce behavior

I used the pygame example for start then I wanted to add a `uniform float time` to my shader. As I run my program it raised the KeyError.

Example fragment shader:
```
#version 330
out vec4 color;
uniform float time; // it's unused, only declared

void main() {
    vec3 col = vec3(0.0);
    //col.r = sin(time)*0.5+0.5;
    //col.g = cos(time)*0.5+0.5;
    //col.b = sin(time*2.0)*0.5+0.5;

    color = vec4(col,1.0);
}
```

Example code:
```
...
prog = ctx.program([vert,frag])
u_time = prog.uniforms['time'] # this raises a KeyError
...
```

### Version info

```
python -m ModernGL
```

This command caused python.exe to crash so I can't put the version info here. I found the version number in the __init__.py file, it is 4.2.0.

**Comment by cprogrammer1994** [comment]
Hi!

Unused uniforms are **inactive** uniforms, so they cannot be listed using OpenGL calls.

Try this:

```py
class FakeUniform:
    value = None

u_time = prog.uniforms.get('time', FakeUniform())
```

[dict.get](https://www.tutorialspoint.com/python/dictionary_get.htm)

---

> This command caused python.exe to crash so I can't put the version info here. I found the version number in the init.py file, it is 4.2.0.

- What is your python version?
- Is it 64 or 32 bit?

**Comment by fekga** [comment]
Alright I already thought about this but was curious why this happened.

I'm using Python 3.4.3 64bit.

**Comment by fekga** [comment]
Your suggestion didn't work as UniformMap is not a dict and has no `get` method.

**Comment by cprogrammer1994** [comment]
Could you make a PR with this new method?
Could you also add it to the other `...Map` classes?
and make `default=None` the default value?
like this: `def get(self, key, default=None)`

**Comment by fekga** [comment]
Sure, I can but this will be my first time. Which branch should should I PR
from?

2017-11-19 18:33 GMT+01:00 Szabolcs Dombi <notifications@github.com>:

**Comment by cprogrammer1994** [comment]
1. Fork the repo
2. create a new branch directly from ModernGL's master.

this [link](https://help.github.com/articles/creating-a-pull-request/) may help.

Thank you!

**Comment by fekga** [comment]
Okay, I think it is done, all tests have passed.

2017-11-20 6:35 GMT+01:00 Szabolcs Dombi <notifications@github.com>:

**Comment by cprogrammer1994** [comment]
merged.

I think I will be able to make a new release this week.
