### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by kunyao** [cprogrammer1994/ModernGL#154]
Great OpenGL wrapper! However, I found two places not convenient to use. I don't know if you have further consideration.
- The First one is about your VAO(generated by vertex_array) design. From my understanding(correct me if I'm wrong), in ModernGL, a VAO is combined with a shader program. What if I want to render the same vertex array with different shader programs? Is there a way to do so without copy the vertex buffer to GPU twice in the current version?

- The second one is about the attributes and uniforms. I think we can only access and claim those active ones in the python scripts outside, right? I used to comment out lines for debugging and testing new features directly, this would result in some attributes and uniforms inactive, I have to go back and comment relative lines in python. It's a minor problem, of course, just a little annoying.

**Comment by Cazadorro** [comment]
>in ModernGL, a VAO is combined with a shader program

Where do you see that?  ModernGL pretty much works exactly like how you would wrap opengl 3.3+ in C++, shaders are attached to *programs*, see https://github.com/cprogrammer1994/ModernGL/blob/master/examples/01_b_simple_color_triangle.py or any of the other examples in the repo for how this works.  If you have problems here, then you have problems with the actual OpenGL API not ModernGL

>The second one is about the attributes and uniforms. I think we can only access and claim those active ones in the python scripts outside, right?

not sure what you mean by this, could you expand on this question?

**Comment by Cazadorro** [comment]
>in ModernGL, a VAO is combined with a shader program.

Example found [here](https://github.com/cprogrammer1994/ModernGL/blob/master/examples/01_b_simple_color_triangle.py)

`self.vao = self.ctx.simple_vertex_array(self.prog, self.vbo, ['in_vert', 'in_color'])`

I think it would make more sense to have something like the following syntax:

    self.vao = self.ctx.simple_vertex_array(self.vbo,....)    
    self.vertex_array_program_object = self.ctx.simple_vertex_array_program_object(self.vao, self.prog, ['in_vert', 'in_color'])

program objects should be able to be used with multiple vaos and likewise *vaos with multiple program objects*

>The second one is about the attributes and uniforms. I think we can only access and claim those active ones in the python scripts outside, right?

Not sure what you mean by this, could you expand on this?

**Comment by kunyao** [comment]
Thanks for the supplement.

For the second point, I mean in the current version the syntax like:
`vao_content = [normal_buffer, '3f', ['normal']]`
`vao = ctx.vertex_array(program, vao_content, ibo)`

would return **error**, if the attribute normal is **inactive** (not related to the final output of fragment shader). This case happens for the uniforms as well. I think it would make more sense to open the access to those inactive ones as well.

**Comment by Cazadorro** [comment]
Ah, OK that makes sense, I see both sides to this.   In a non-debug program, it would never make sense to even utilize inactive uniforms, and in such a program using them should probably result in an error.  But in a debugging program, inactive uniforms are typically temporary situations.   I could see a change that if the debug option was passed to the interpreter that those errors would not be errors, but warnings maybe?  I don't know enough about how this framework works on the inside to make such a change, if I have the time I might try to put this functionality in.

**Comment by cprogrammer1994** [comment]
There will be a workaround for 2. in ModernGL5

**Comment by Cazadorro** [comment]
what about for one? That one seems easier to deal with, and honestly appears more important.

**Comment by cprogrammer1994** [comment]
**You don't have to duplicate vertex data.** Just create multiple **vertex_arrays** that use the **same** buffer.

```py
vbo1 = ctx.buffer(...)
vbo2 = ctx.buffer(...)

vao1 = ctx.simple_vertex_array(prog1, vbo1, ['in_vert', 'in_norm', 'in_texcoord'])
vao2 = ctx.simple_vertex_array(prog2, vbo1, ['in_vert', 'in_norm', 'in_texcoord'])
vao3 = ctx.vertex_array(prog3, [
    (vbo1, '3f3f2f', ['in_vert1', 'in_norm2', 'in_texcoord1']),
    (vbo2, '3f3f2f', ['in_vert2', 'in_norm2', 'in_texcoord2']),
])
vao4 = ctx.vertex_array(prog1, [  # using in_vert, in_norm from the first buffer, in_texcoord from the second
    (vbo1, '3f3f8x', ['in_vert', 'in_norm']),
    (vbo2, '12x12x2f', ['in_texcoord']),
])
...
```

Creating a vertex array object is considered a low cost operation. (time & memory)

**Comment by Cazadorro** [comment]
It would be great if this were in the documentation somewhere, and this solves the memory issue completely.  I guess its possible that switching vertex arrays has driver overhead, but I'm not sure if it works like that since any given AMD or NVIDIA driver is probably sending the address of the arguments used for any given shader kernel on the GPU any way each time it tells it to use a specific shader (so per render loop), especially since most gaming GPUs use a unified pipeline which means you'll need to tell the gpu to switch programs and supply appropriate arguments each time anyway for vertex, fragment, geometry, compute etc...

**Comment by cprogrammer1994** [comment]
In ModernGL5 Program members are stored in the same dictionary.

```py
program = ctx.program(...)
```

**Comment by cprogrammer1994** [comment]
Examples cover how to reuse a buffer with multiple vaos.

**Comment by kunyao** [comment]
I notice that we do have fake uniforms now, but we don't have fake varyings. 
so, my previous question remains open.

`vao_content = [normal_buffer, '3f', ['normal']]`
`vao = ctx.vertex_array(program, vao_content, ibo)`

How to write the code if I want to send normal varying to the shader, but don't want to use it for the moment?
