### ISSUE TITLE
The name of the package

### ISSUE THREAD

**Issue by godaygo** [cprogrammer1994/ModernGL#160]
Of course it's a matter of taste, but maybe it is not too late to rename the package name to all-lowercase style to follow PEP8: [Package and Module Names ](https://www.python.org/dev/peps/pep-0008/#package-and-module-names).

to be `import moderngl` 
instead of the current `import ModernGL`

**Comment by cprogrammer1994** [comment]
Thank you for pointing it out! I will consider this change before releasing ModernGL 5.x.x

**Comment by cprogrammer1994** [comment]
https://github.com/cprogrammer1994/ModernGL/commit/81c8cf5029db901d132226c110ec912962d108a7
