### ISSUE TITLE
Shadowmapping example

### ISSUE THREAD

**Issue by jakebruce** [cprogrammer1994/ModernGL#161]
Hi there, thanks for your work on this very promising wrapper.

It would be nice to have a shadow mapping example. I've been trying to implement basic shadow mapping according to a [tutorial](http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-16-shadow-mapping/) but I'm unsure how to do some of it (and whether it's even implemented) in the ModernGL API.

For example, according to [this stackoverflow post](https://stackoverflow.com/questions/22419682/glsl-sampler2dshadow-and-shadow2d-clarification) it is import to set `GL_TEXTURE_COMPARE_MODE` = `GL_COMPARE_REF_TO_TEXTURE​`. Is this implemented in ModernGL?

I'm also wondering about depth textures as render targets (without a color attachment). Is this possible in ModernGL? Do we have to use a framebuffer with a dummy color attachment that we then ignore?

Cheers!

**Comment by cprogrammer1994** [comment]
Hi! Great catch! I will add the missing `GL_TEXTURE_COMPARE_MODE` for depth textures. depth_textures will have a setter for `GL_TEXTURE_COMPARE_FUNC` too.

- [glTexParameter](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexParameter.xhtml)

**Comment by cprogrammer1994** [comment]
> I'm also wondering about depth textures as render targets (without a color attachment). Is this possible in ModernGL? Do we have to use a framebuffer with a dummy color attachment that we then ignore?

Currently framebuffers must have at least 1 color attachment. I will investigate what will happen if I remove that check.

**Comment by cprogrammer1994** [comment]
In ModernGL5 Framebuffers can have 0 color_attachments if a depth_attachment was provided.
I will add an example soon.

Textures have a getsetter for `compare_func` (available if the texture is a depth texture)
The `GL_TEXTURE_COMPARE_MODE` is set by default.
