### ISSUE TITLE
ModuleNotFoundError: No module named 'ModernGL'

### ISSUE THREAD

**Issue by cprogrammer1994** [cprogrammer1994/ModernGL#166]
This happens when projects depending on ModernGL4 unfortunately upgrade to ModernGL5

You can install ModernGL4 with the following command:

```
python -m pip install "ModernGL<5.0.0"
```

ModernGL4 is still supported. Please see the [ModernGL4](https://github.com/cprogrammer1994/ModernGL/tree/ModernGL4) branch.

**Comment by nasser225** [comment]
Just for those having this issue, I changed the ModernGL folder name to lowercase to match the mgl5 style, under the Python installation directory in the library folders and it worked for me.

My directory was C:\Python3\Lib\site-packages\moderngl
