### ISSUE TITLE
Segmentation fault with auto-completion in ipython 

### ISSUE THREAD

**Issue by kunyao** [cprogrammer1994/ModernGL#167]
In the version 5.x, the auto-completion for context functions will cause Ipython to dump with segmentation fault

Basically like, 
ctx = moderngl.create_context()
ctx.[tab]...

segmentation fault!

This does not happen in the previous version.
(I test with python 3.6.2 Ipython 6.1.0 ModernGL 5.0.2)

**Comment by cprogrammer1994** [comment]
Thank you for the bug report!

I was able to reproduce it.

![image](https://user-images.githubusercontent.com/11232402/36776453-81b57c14-1c6e-11e8-8b4d-901eda9d9723.png)

**Comment by cprogrammer1994** [comment]
The segmentation fault was caused by the new `Error` class introduced in ModernGL5. The segmentation fault does not happen if no error was thrown earlier. Can you please verify if you still get segmentation fault?

```
pip install ModernGL>=5.0.3
```

![image](https://user-images.githubusercontent.com/11232402/36793892-5c511580-1ca7-11e8-895a-f4bd0eb51ed1.png)

**Comment by kunyao** [comment]
still...
![image](https://user-images.githubusercontent.com/5549300/36885136-1dac7d04-1e20-11e8-8c2d-3ee6e9463dea.png)

**Comment by cprogrammer1994** [comment]
What OS do you use?
please also print the `python --version`

**Comment by kunyao** [comment]
Archlinux
python 3.6.3 from Anaconda
64bit

**Comment by cprogrammer1994** [comment]
How do you initialize a window or opengl context?

**Comment by kunyao** [comment]
I create a pyglet window as:
pyglet.window.Window()

**Comment by kunyao** [comment]
Emm... bug fixed after upgrading ipython to 6.2.1

**Comment by cprogrammer1994** [comment]
Good news then!
I was testing with the latest ipython. I was not able to reproduce the segfault
