### ISSUE TITLE
MultiDrawIndirect example??

### ISSUE THREAD

**Issue by nasser225** [cprogrammer1994/ModernGL#168]
Is there any example using this OpenGL feature / extension?

Also I am trying to specifically create a particle system of at least 1 000 000 (1M) particles and be able to run at least 30FPS. I have successfully implemented a Transform Feedback program and have tried to couple this with the MGL 5 render_indirect command, but get a blank screen.

Please advise..

**Comment by cprogrammer1994** [comment]
[This](https://github.com/cprogrammer1994/ModernGL/blob/master/examples/experimental/texture_array_and_indirect_draw.py) is the only example for now.

This feature is still experimental, it requires OpenGL 4.3+.

If all the particles have the same shape, you can use instanced rendering instead:

- create a vertex buffer with the vertices of a single particle (for example a unit circle)
- reuse your particle system's buffer and assign it to a vertex array:

```py
vao = ctx.vertex_array(prog, [
  (single_particle_vbo, '2f', 'in_vert1'),
  (particle system_vbo, '2f 8x/i', 'in_vert2'),  # please note the /i in the buffer format
]
```

- use instanced rendering

```py
vao.render(ModernGL.TRIANGLE_FAN, instances=...)
```

Take a look at the [instanced_rendering_crates.py](https://github.com/cprogrammer1994/ModernGL/blob/master/examples/instanced_rendering_crates.py)

**Comment by nasser225** [comment]
Hi Szabolcs, 

I implemented the instanced rendering method but it allows me to render only 5000 particles / points and the frame rate drops to 20FPS. No where near the 1million I need. I am not even translating them at all(!).

Surprisingly I can get much better numbers (500k+) with FPS using standard VBOs, VAOs and draw commands...it's just that I thought I would achieve this and better performance (2million+? points) using instancing, but it seems to be opposite...

This is what I have in my current instancing test:

position_buffer = ctx.buffer(positions.astype('f4').tobytes())

vao_content = [
            (vertex_buffer, '2f', ['vert']),
            (position_buffer, '2f2f/i', ['instance_pos','velocity']),
        ]

vao1 = ctx.vertex_array(prog, vao_content)
...
vao1.render(ModernGL.POINTS,instances=len(positions))

Any ideas?

**Comment by cprogrammer1994** [comment]
In your code:

```py
vao1.render(ModernGL.POINTS,instances=len(positions))
```

will become:

```py
vao1.render(ModernGL.POINTS, vertices=vertex_buffer.size//8, instances=len(positions))
```

> vertices=vertex_buffer.size//8 is the maximum number of vertices possible to render (the default) 8 comes from the size of `2f` (2 floats)

Please paste the buffer creation here, if not possilbe please print the size of each buffer, for example: `print(vertex_buffer.size)`

**Comment by nasser225** [comment]
The positions buffer is created like so:

x = np.random.uniform(-0.5,0.5,pNum)
y = np.random.uniform(0.0,0.2,pNum)
shape = (pNum,4) # rows, columns
data = np.zeros(shape,dtype=float)
data[:,0] = x
data[:,1] = y

positions = data

position_buffer = ctx.buffer(positions.astype('f4').tobytes())
