### ISSUE TITLE
Inserting / Drawing ONE (1) object at a time...

### ISSUE THREAD

**Issue by nasser225** [cprogrammer1994/ModernGL#169]
How can this be done with ModernGL. I want the objects to appear on the screen over time.

Currently I am creating all vertex positions for particles in a buffer, uploading into a VAO as usual and of course all get render with the render command. The problem is they are all visible on the screen at once and I want to 'stream' them over x time step. 

Please advise,

Thanks

**Comment by cprogrammer1994** [comment]
Create a large buffer that will be capable of storing all the vertices.

Read the docs of [render()](http://moderngl.readthedocs.io/en/stable/reference/vertex_array.html#moderngl.VertexArray.render).

manually set `vertices=` or `instances=` depending on what you want to render.

**Comment by nasser225** [comment]
Hi Szabolcs,

Would you mind elaborating with a simplistic example even? I couldn't find any example in the directory that shows something like this.

Do I create a VBO with null data to begin with? Then add data to it during draw? Would be great if you can clarify. 

Many thanks,

**Comment by cprogrammer1994** [comment]
If you want to render 1 point / particle, you will not need instanced rendering or multidraw.

Check out this [example](https://github.com/cprogrammer1994/ModernGL/blob/master/examples/particle_system.py)

- reserve a big buffer for example `ctx.buffer(reserve='16MB')  # 2097152 * (size of 2f)`
- fill the buffer with a couple of points
- render with `vao.render(moderngl.POINTS, vertices=num_points)  # transform the same way`

**Comment by nasser225** [comment]
Where is the runtime reference? How will I get control over the number of particles rendered / inserted per x amount of time?

**Comment by cprogrammer1994** [comment]
![image](https://user-images.githubusercontent.com/11232402/36898089-029f8df6-1e22-11e8-9220-b695dd35f44e.png)

Here is an improved version of the particle system example.

```py
import moderngl
from moderngl_examples import run_example
import numpy as np


def particles(count):
    a = np.random.uniform(0.0, np.pi * 2.0, count)
    r = np.random.uniform(0.0, 1.0, count)
    return np.dstack([
        np.zeros(count),
        np.zeros(count),
        np.cos(a) * np.sqrt(r) * 0.001 - 0.003,
        np.sin(a) * np.sqrt(r) * 0.001 - 0.008,
    ]).astype('f4').tobytes()


class Example:
    def __init__(self, wnd):
        self.wnd = wnd
        self.ctx = moderngl.create_context()

        self.prog = self.ctx.program(
            vertex_shader='''
                #version 330

                in vec2 in_vert;

                void main() {
                    gl_Position = vec4(in_vert, 0.0, 1.0);
                }
            ''',
            fragment_shader='''
                #version 330

                out vec4 f_color;

                void main() {
                    f_color = vec4(0.30, 0.50, 1.00, 1.0);
                }
            ''',
        )

        self.transform = self.ctx.program(
            vertex_shader='''
            #version 330

            uniform vec2 Acc;

            in vec2 in_pos;
            in vec2 in_prev;

            out vec2 out_pos;
            out vec2 out_prev;

            void main() {
                out_pos = in_pos * 2.0 - in_prev + Acc;
                out_prev = in_pos;
            }
        ''',
            varyings=['out_pos', 'out_prev']
        )

        self.acc = self.transform['Acc']
        self.acc.value = (0.0, -0.0001)

        self.vbos = [
            self.ctx.buffer(reserve='32MB', dynamic=True)
            for i in range(3)
        ]

        self.transform_vaos = [
            self.ctx.simple_vertex_array(self.transform, self.vbos[i], 'in_pos', 'in_prev')
            for i in range(3)
        ]

        self.render_vaos = [
            self.ctx.vertex_array(self.prog, [(self.vbos[i], '2f 2x4', 'in_vert')])
            for i in range(3)
        ]

        self.num_points = 0
        self.idx = 0

    def render(self):
        self.ctx.viewport = self.wnd.viewport
        self.ctx.clear(1.0, 1.0, 1.0)
        self.ctx.point_size = 2.0

        new_points = 400
        if self.num_points + new_points <= 2 * 1000 * 1000:
            self.vbos[self.idx].write(particles(new_points), offset=self.num_points * 16)
            self.num_points += new_points
            if self.num_points % (new_points * 100) == 0:
                print(self.num_points)

        next_idx = (self.idx + 1) % 3
        self.render_vaos[self.idx].render(moderngl.POINTS, self.num_points)
        self.transform_vaos[self.idx].transform(self.vbos[next_idx], moderngl.POINTS, self.num_points)
        self.idx = next_idx


run_example(Example)
```

I have 2M points transformed. most of them gets discarded due to they will fall out of screen. I have 60fps with a GTX 1050 (Notebook)

---

> Where is the runtime reference?

http://moderngl.readthedocs.io/en/stable/reference/index.html

> How will I get control over the number of particles rendered / inserted per x amount of time?

Set the `vertices=` parameter and the `instances=` parameter of the `render` method.

http://moderngl.readthedocs.io/en/stable/reference/vertex_array.html#moderngl.VertexArray.render

**Comment by nasser225** [comment]
That shows me how to regulate the number of particles over time - thanks. However, the ultimate goal of my project is to keep all of the particles inserted within the domain / simulation screen. 

Ideally (ultimately):
- 3-5Million particles - more is better! - this becomes the max_count of particles in domain
- All inserted in the domain, none discarded
- Looking forward, these will be 3D points with the usual particle movement and collision detection
- Particles will collide with each other AND a 3D object i.e. box (maybe around 5000 triangles max)

How can I best achieve such a project using ModernGL?

Thanks a lot

**Comment by nasser225** [comment]
Hi, 

Is my ideal simulation possible here or not? I may have to resort to using PyopenGL in order to do a direct side-by-side method test to see which works best for my particular case. 

Using ModernGL was great for ease but I think it's not intuitive enough and hides the detail of OpenGL so it becomes difficult to understand and relate the tutorials for OpenGL online.

Thanks anyway for your help.
