### ISSUE TITLE
vertex_shader version '330' is not supported

### ISSUE THREAD

**Issue by aarbour** [cprogrammer1994/ModernGL#172]
### Should render a line strip
When trying the example below, I am getting version 330 not supported. I can change it to 130 ... to 410 and it presents the same issue (replacing 330 with whatever number)

### Actual behavior

vertex_shader
ERROR: 0:2: '' :  version '330' is not supported

### Steps to reproduce behavior

Use the code below on a **Mac 10.13.3** - Macbook Pro Mid 2015

### ModernGL 5.0.4

```
import cyglfw3 as glfw
import moderngl as mgl
import numpy as np


def window_close_change(window):
    glfw.SetWindowCloseCallback(window, True)

def main():
    if not glfw.Init():
        exit()

    window = glfw.CreateWindow(640, 480, "HELLO WORLD")
    if not window:
        glfw.Terminate()
        exit()

    glfw.WindowHint(glfw.RESIZABLE, True)
    glfw.WindowHint(glfw.CONTEXT_VERSION_MAJOR, 3)
    glfw.WindowHint(glfw.CONTEXT_VERSION_MINOR, 3)
    glfw.WindowHint(glfw.OPENGL_FORWARD_COMPAT, True)
    glfw.WindowHint(glfw.OPENGL_PROFILE, glfw.OPENGL_CORE_PROFILE)


    # The window is being closed
    glfw.SetWindowCloseCallback(window, window_close_change)
    glfw.MakeContextCurrent(window)

    context = mgl.create_context()
    program = context.program(
        vertex_shader='''
            #version 330

            in vec2 in_vert;
            in vec3 in_color;

            out vec3 v_color;

            void main() {
                v_color = in_color;
                gl_Position = vec4(in_vert, 0.0, 1.0);
            }
        ''',
        fragment_shader='''
            #version 330

            in vec3 v_color;

            out vec3 f_color;

            void main() {
                f_color = v_color;
            }
        ''',
    )

    x = np.linspace(-1.0, 1.0, 50)
    y = np.random.rand(50) - 0.5
    r = np.ones(50)
    g = np.zeros(50)
    b = np.zeroes(50)

    verts = np.dstack([x, y, r, g, b])

    vbo = context.buffer(verts.astype('f4').tobytes())
    vao = context.simple_vertex_array(program, vbo, 'in_vert', 'in_color')
    fbo = context.simple_framebuffer((512, 512))
    fbo.use()
    fbo.clear(0.0, 0.0, 0.0, 1.0)



    while not glfw.WindowShouldClose(window):
        # Render here
        #vao.render(mgl.LINE_STRIP)

        glfw.SwapInterval(1)
        glfw.SwapBuffers(window)
        glfw.PollEvents()

    glfw.Terminate()

main()
```

```
vertex_shader
=============
ERROR: 0:2: '' :  version '330' is not supported
```

**Comment by cprogrammer1994** [comment]
Please add the following lines below `context = mgl.create_context()`:

```py
print(context.info['GL_VERSION'])  # string version
print(context.version_code)  # major version * 100 + minor version * 10 (should print at least 330)
print(context.error)  # should be GL_NO_ERROR
```

**Comment by aarbour** [comment]
So this is an odd result:
2.1 INTEL-10.30.14
0
GL_INVALID_ENUM

**Comment by cprogrammer1994** [comment]
run `glxinfo | grep "OpenGL version"`

please see: [Mac computers that use OpenCL and OpenGL graphics](https://support.apple.com/en-us/HT202823)

---

Try to disable this:

```
glfw.WindowHint(glfw.OPENGL_FORWARD_COMPAT, True)  # set it to False
```

---

Try to print the opengl version using glfw.

**Comment by aarbour** [comment]
So I've noticed that the WindowHints are not working. I changed resizable to False and it is still resizable. I added visible as False and it still showed. I am wondering if something is wrong with glfw (using cyglfw3).

**Comment by aarbour** [comment]
Ok - I finally got it to work. I switched to a different glfw package and noticed that I was calling my hints, creates and context in the wrong order. Since doing that, I now have:
4.1 INTEL-10.30.14
410
GL_INVALID_ENUM

But what is causing the invalid enum?

**Comment by cprogrammer1994** [comment]
When you first access the info property. A lot of glGet calls get executed. Some of them may require OpenGL 4.3 (for example shader storage buffer limits or similar). This does not cause further errors. The only drawback is that the info will contain keys with value = 0. I will take a look at those calls.
