### ISSUE TITLE
Ability to customize which texture interpolation method is used

### ISSUE THREAD

**Issue by CharlieCodex** [cprogrammer1994/ModernGL#174]
Hi y'all, I was recently taking a peak at the docs and noticed no way to specify which sampling method is used. Going a step deeper it looked like it was hard-coded to GL_LINEAR in the Texture.cpp file. I would love some way to access the glTexParameter* family without tweaking and building from source. I did however notice that these values are exposed via moderngl.LINEAR and so on.

I'm on moderngl5 on OsX, but I think this more falls under feature request or sheer lack of intelligence on my part.

Thanks,

**Comment by cprogrammer1994** [comment]
Hi!

You can set the texture.filter as follows:

```py
texture.filter = (moderngl.NEAREST, moderngl.NEAREST)
```

The first one is the min filter. The second is the mag filter.

docs: https://moderngl.readthedocs.io/en/stable/reference/texture.html#moderngl.Texture.filter

**Comment by cprogrammer1994** [comment]
solved, closing...
