### ISSUE TITLE
Ubuntu 16.04 GLSL 3.30 is not supported

### ISSUE THREAD

**Issue by lavinrp** [cprogrammer1994/ModernGL#176]
### Issue

In Ubuntu 16.04 on Intel(R) Core(TM) i5-3317U CPU and no dedicated graphics card  shader compilation fails with the following exception:

> File "/my_path/lib/python3.6/site-packages/moderngl/__init__.py", line 2875, in program
>     varyings
> mgl.Error: GLSL Compiler failed
> 
> vertex_shader
> \=============
> 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

The machine experiencing this issue returns the following output after running "glxinfo | grep "version""

> server glx version string: 1.4
> client glx version string: 1.4
> GLX version: 1.4
>     Max core profile version: 4.2
>     Max compat profile version: 3.0
>     Max GLES1 profile version: 1.1
>     Max GLES[23] profile version: 3.0
> OpenGL core profile version string: 4.2 (Core Profile) Mesa 17.2.8
> OpenGL core profile shading language version string: 4.20
> OpenGL version string: 3.0 Mesa 17.2.8
> OpenGL shading language version string: 1.30
> OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.2.8
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

The machine that is experiencing this issue is dual booted with windows. When running Windows 10 the same hardware is capable of using ModernGL without issue.

The same issue has been reproduced on several Ubuntu 16.04 laptops and one Mac laptop (I do not have any more information on these machines at this time, but can acquire it if it would be helpful). We have been unable to produce the issue on any Windows 10 install.

We have not attempted to reproduce this issue on an Ubuntu install with dedicated graphics hardware.

When searching to see if the issue was on our end we came across [this](https://github.com/hannorein/rebound/issues/284) issue with similar symptoms.

### Version info

moderngl 5.0.7
\--------------
vendor: Intel Open Source Technology Center
renderer: Mesa DRI Intel(R) Ivybridge Mobile 
version: 4.2 (Core Profile) Mesa 17.2.8
python: 3.6.3 (default, Oct  4 2017, 14:11:28) 
[GCC 6.3.0 20170519]
platform: linux
code: 420

**Comment by cprogrammer1994** [comment]
I will implement this method: https://github.com/cprogrammer1994/ModernGL/issues/177
And will add some notes to the docs.

**Comment by lavinrp** [comment]
Thanks for the quick turnaround time.

We are using wxPython. I'll see if I can figure out how to require the core profile.

**Comment by cprogrammer1994** [comment]
It looks like [`wx.glcanvas.GLCanvas.__init__`](https://wxpython.org/Phoenix/docs/html/wx.glcanvas.GLCanvas.html#wx.glcanvas.GLCanvas.__init__) can take a `attribList` similar to the attrib list in [GLX_ARB_create_context](https://www.khronos.org/registry/OpenGL/extensions/ARB/GLX_ARB_create_context.txt).

Not 100% sure but `[0x9126, 1, 0]` should work fine on linux and windows too.

**Comment by lavinrp** [comment]
That didn't quite work, but you were on the correct track.
[WX_GL_CORE_PROFILE, WX_GL_DOUBLEBUFFER, 0] got things working on linux for me. Windows doesn't like it though.

A simple OS check with an environment variable override (gross, I know) can plug the hole until we find a more permanent solution.
Its clear that our issues are on our end though.

Thanks again. You really sped up our fix time on this and we appreciate it.
