### ISSUE TITLE
VertexArray.bind with offset fails for mat2 but not for vec4.

### ISSUE THREAD

**Issue by wpk-** [cprogrammer1994/ModernGL#182]
### Issue

*Summary*: a `vec4` takes 16 bytes of buffer space, so two of them fit in a 32 byte buffer. I set up a program that runs for 1 vertex and all it does is copy the value to the output. I run it without offset argument, with zero offset, and with offset=16. All tests run fine. If I replace `vec4` with `mat2` however (also 16 bytes), the test with offset=16 fails with the following result:

```
- (4.0, 5.0, 2.0, 3.0)
?            ^    ^

+ (4.0, 5.0, 6.0, 7.0)
?            ^    ^
 : Copy mat2 failed with vao.bind, offset = 16.
```

[Full test file in this gist.](https://gist.github.com/wpk-/ea1d20c57cce214ffc46c8b413035411)

I'm starting to feel this is an Intel issue. If this is the case, can you please advise me what's the best place to post this? (If I post moderngl code somewhere, I'm guessing people say they can't see the OpenGL function calls.)

### Version info

```
python -m moderngl
```

```
moderngl 5.0.7
--------------
vendor: Intel
renderer: Intel(R) HD Graphics 4000
version: 4.0.0 - Build 10.18.10.4885
python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
platform: win32
code: 400
```

**Comment by cprogrammer1994** [comment]
Do you bind 4 locations when binding mat4?

**Comment by wpk-** [comment]
`vao.bind(in_location, 'f', vbo1, '4f', offset=16)` binds four floats. This is identical between `vec4` and `mat2` afaik. I didn't try `mat4`.

**Comment by cprogrammer1994** [comment]
a `mat2` reserves 2 vertex attributes (2 x vec2 = mat2)

in the following example location 0 and location 1 is taken by `in mat2 in_vert`

```py
import struct
import moderngl

ctx = moderngl.create_standalone_context()
prog = ctx.program(vertex_shader='''
    #version 330

    in mat2 in_vert;
    out mat2 out_vert;

    void main() {
        out_vert = in_vert;
    }
''', varyings=['out_vert'])
b0 = ctx.buffer(struct.pack('4f', 99.0, 99.0, 99.0, 99.0))
b1 = ctx.buffer(struct.pack('4f', 1.0, 2.0, 3.0, 4.0))
b2 = ctx.buffer(struct.pack('4f', 5.0, 6.0, 7.0, 8.0))
vao = ctx.simple_vertex_array(prog, b0, 'in_vert')
vao.bind(0, 'f', b1, '2f')  # comment this
vao.bind(1, 'f', b2, '2f')  # or comment this
vao.transform(b2, moderngl.POINTS, 1)
print(struct.unpack('4f', b2.read()))
```

**Comment by cprogrammer1994** [comment]
I believe in most of the cases `vao = ctx.vertex_array(...)` is enough. I don't know about any "best practices" that cannot be done using it. Regardless of whether moderngl implements vao.bind() for the rest of the cases. It should have a better documentation and maybe a couple of examples.

From the example above `vao.bind(0, 'f', b1, '2f')` is equivalent to `glVertexAttribPointer(0, 2, GL_FLOATS, False, 0, 0); // where b1 is bound properly`

The second parameter (the `'f'`) is only used to determine what gl function must be called:

```c++

	switch (type[0]) { // type parameter must be 'f', 'i' or 'd' and it is not checked for invalid values
		case 'f':
			gl.VertexAttribPointer(location, node->count, node->type, normalize, stride, ptr);
			break;
		case 'i':
			gl.VertexAttribIPointer(location, node->count, node->type, stride, ptr);
			break;
		case 'd':
			gl.VertexAttribLPointer(location, node->count, node->type, stride, ptr);
			break;
		default:
			MGLError_Set("invalid type");
			return 0;
	}
```

**Comment by cprogrammer1994** [comment]
VertexArray.bind works correctly. Some vertex attributes have more then one locations and those should be bound too. For example matrices and arrays can have more then 1 vertex array locations.
