### ISSUE TITLE
Cannot create OpenGL context on server

### ISSUE THREAD

**Issue by thigitogatiamas** [cprogrammer1994/ModernGL#189]
Hello,

I was trying to use this library on a remote server without a display. Thus, I got the error:

> Cannot create context

Are there any solutions how to do headless / offline-rendering using `ModernGL` ?

**Comment by cprogrammer1994** [comment]
Hi!

Here is an example where ModernGL is used to render a model on a server:

https://github.com/cprogrammer1994/ubuntu-headless-ModernGL/blob/master/README.md

When ModernGL is used to render in headless mode you will not need any window implementations and the context must be created using `moderngl.create_standalone_context`.

The error you provided does not match any error messages in the latest version. Are you sure this error comes from ModernGL?
Can you paste a stack trace?

**Comment by thigitogatiamas** [comment]
Hi,
okay I followed the example and still got the same result. I am using Amazon AWS with an Ubuntu instance (p2.large). 

Since I followed your example and I installed `ModernGL` rather than `moderngl` I get the following output as version:

```
(pytorch_p36) ubuntu@ip:~/test/Headless-rendering-with-python$ python -m ModernGL --version
ModernGL 4.2.2
```

And following your example (I installed everything)

```
(pytorch_p36) ubuntu@ip-:~/test$ export DISPLAY=:99.0
(pytorch_p36) ubuntu@ip-:~/test$ 
(pytorch_p36) ubuntu@ip-:~/test$ Xvfb :99 -screen 0 640x480x24 &
[1] 2978
(pytorch_p36) ubuntu@ip-:~/test$ git clone https://github.com/cprogrammer1994/Headless-rendering-with-python
Cloning into 'Headless-rendering-with-python'...
remote: Counting objects: 81, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 81 (delta 0), reused 0 (delta 0), pack-reused 77
Unpacking objects: 100% (81/81), done.
Checking connectivity... done.
(pytorch_p36) ubuntu@ip-:~/test$ cd Headless-rendering-with-python/
(pytorch_p36) ubuntu@ip-:~/test/Headless-rendering-with-python$ python main.py
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    ctx = ModernGL.create_standalone_context()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ModernGL/context.py", line 822, in create_standalone_context
    ctx = Context.new(mgl.create_standalone_context(*size))
mgl.Error: cannot create OpenGL context
```

I am logging into the server the standard way with ssh:

 `ssh user@ip`

Am I missing something?

**Comment by cprogrammer1994** [comment]
I was not able to launch a `p2.___` instance yet. I hope I will get my help asap from aws support.

1. Do you have an `Xvfb` running?
2. I recommend to use moderngl 5.x.x
3. I have found out that some of the examples are using the older version of moderngl. An up2date example for headless rendering is [here](https://github.com/cprogrammer1994/Headless-rendering-with-python/blob/master/main.py)
4. Please install `mesa-utils` then try to run the following lines:

```
export DISPLAY=:99.0
Xvfb :99 -screen 0 640x480x24 &
sleep 1
glxinfo | grep "OpenGL version"
python3 main.py  # try to run the file from 3.
```

**Comment by thigitogatiamas** [comment]
Do you have an Xvfb running?
Yes I do:
```
(pytorch_p36) ubuntu@ip-:~/test$ Xvfb :99 -screen 0 640x480x24 &
[1] 2978
```
I recommend to use moderngl 5.x.x

Well, I wanted to, but in moderngl 5.x.x there is no vertex and fragment shader anymore and also I could not set my texture filter to linear anymore. The documentation in that regard is not helpful at all that is why I decided to stay with version 4.2.x

I have found out that some of the examples are using the older version of moderngl. An up2date example for headless rendering is here
Thank you!

Please install mesa-utils then try to run the following lines:
...

Will do!

**Comment by thigitogatiamas** [comment]
Yeah I still want to have the vertex shader and the fragment shader in a single file rather as a string.

**Comment by thigitogatiamas** [comment]
Okay, I have changed my code from:

```
      # self.prog_eep = self.ctx.program(vertex_shader=load_shader("exitpoints.vert"), fragment_shader=load_shader("exitpoints.frag"))
        # self.prog_rc = self.ctx.program(vertex_shader=load_shader("raycasting.vert"), fragment_shader=load_shader("raycasting.frag"))
        #
        # # re-attach vertex array objects
        # vbo_attributes = ['VerPos']
        # vbo_format = ModernGL.detect_format(self.prog_eep, vbo_attributes)
        # self.vao_eep = self.ctx.vertex_array(self.prog_eep, [(self.vbo_vertex, vbo_format, vbo_attributes[0])], self.vbo_veridx)
        # vbo_format = ModernGL.detect_format(self.prog_rc, vbo_attributes)
        # self.vao_rc = self.ctx.vertex_array(self.prog_rc, [(self.vbo_vertex, vbo_format, vbo_attributes[0])], self.vbo_veridx)
        #
        # # update handles for the uniforms
        # self.unf_screensize = self.prog_rc["ScreenSize"]
        # self.unf_stepsize = self.prog_rc["StepSize"]
        # self.unf_exitpoints = self.prog_rc["ExitPoints"]
        # self.unf_volumetex = self.prog_rc["VolumeTex"]
```

To:

      ```
  self.prog_eep = self.ctx.program([
            self.ctx.vertex_shader(load_shader("exitpoints.vert")),
            self.ctx.fragment_shader(load_shader("exitpoints.frag")),
        ])

        self.prog_rc = self.ctx.program([
            self.ctx.vertex_shader(load_shader("raycasting.vert")),
            self.ctx.fragment_shader(load_shader("raycasting.frag")),
        ])

        # re-attach vertex array objects
        vbo_attributes = ['VerPos', ]
        vbo_format = ModernGL.detect_format(self.prog_eep, vbo_attributes)
        self.vao_eep = self.ctx.vertex_array(self.prog_eep, [(self.vbo_vertex, vbo_format, vbo_attributes)],
                                             self.vbo_veridx)

        vbo_format = ModernGL.detect_format(self.prog_rc, vbo_attributes)
        self.vao_rc = self.ctx.vertex_array(self.prog_rc, [(self.vbo_vertex, vbo_format, vbo_attributes)],
                                            self.vbo_veridx)

        # update handles for the uniforms
        self.unf_screensize = self.prog_rc.uniforms["ScreenSize"]
        self.unf_stepsize = self.prog_rc.uniforms["StepSize"]
        self.unf_exitpoints = self.prog_rc.uniforms["ExitPoints"]
        self.unf_volumetex = self.prog_rc.uniforms["VolumeTex"]
```

After that it is not working anymore. I assume there is a bug in my program, however, this behaviour is a bit suspicious

**Comment by thigitogatiamas** [comment]
I just set up a completely new p2.large instance with ubuntu and downloaded `mesa-utils` and `xvfb`. When I try to do what you said I get:


```
root@ip-172-31-24-207:/home/ubuntu# Xvfb :99 -screen 0 640x480x24 &
[1] 3082
root@ip-172-31-24-207:/home/ubuntu# glxinfo | grep "OpenGL version"
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  37
  Current serial number in output stream:  38
```

Are you sure I do not need to do x11 forwarding or anything else?

**Comment by cprogrammer1994** [comment]
![image](https://user-images.githubusercontent.com/11232402/41079625-347d5218-6a2b-11e8-95f5-14056ce4e363.png)

I have run these commands on a simple droplet, not on a `p2.__`.

**Comment by thigitogatiamas** [comment]
Okay,
is there a way to integrate [PEGL](https://github.com/perey/pegl) ?

**Comment by cprogrammer1994** [comment]
I had EGL support in a couple of versions. It turned out it does not support OpenGL 3.3 so I reverted those changes. I will link a specific version soon.

**Comment by thigitogatiamas** [comment]
That would be great! I just noticed tho that even EGL makes use of X11. Well, lets find out if I can get it work with EGL on this remote server without root access. This is my last resort.

**Comment by thigitogatiamas** [comment]
Have you got any other idea how to get your code running without access to X11, nvidia-xconfig, etc. The glxinfo command has never been working so far. I guess as long as this command only throws error I will not be able to get it done?

**Comment by cprogrammer1994** [comment]
ModernGL==5.0.4 have EGL support.

This was an experiment to add support for other backend (EGL, X11, OSMesa).

Useful links to source:

- https://github.com/cprogrammer1994/ModernGL/blob/5.0.4/src/GLContext.cpp#L79
- https://github.com/cprogrammer1994/ModernGL/blob/5.0.4/src/GLContext.cpp#L723
- https://github.com/cprogrammer1994/ModernGL/blob/5.0.4/moderngl/__init__.py#L3105

All you have to do is to install this version and call `create_standalone_context(backend='EGL')`
If the call succeed please try to print the OpenGL version. If the version is above 3.3 I will restore the EGL support form ModernGL

If you manage to print the OpenGL version without ModernGL and the version is above to 3.3. It is possible that I will be able to make ModernGL work there.

**Comment by thigitogatiamas** [comment]
Okay, I changed my version to `5.0.4` and tried to adjust my code as good as possible, however, after `create_standalone_context(backend='EGL')` I cannot execute following lines in my code anymore:

```
glEnable('Anything')
glEnable(GL_CULL_FACE)
glCullFace(GL_FRONT)
```

```
OpenGL.error.GLError: GLError(
	err = 1280,
	description = b'invalid enumerant',
	baseOperation = glEnable,
	cArguments = (GL_ALPHA_TEST,)
)
```

**Comment by thigitogatiamas** [comment]
> If you manage to print the OpenGL version without ModernGL and the version is above to 3.3. It is possible that I will be able to make ModernGL work there.

I do not think I will be.

As I have already said if I execute following lines of code:

```
export DISPLAY=:99.0
Xvfb :99 -screen 0 640x480x24 &
sleep 1
glxinfo | grep "OpenGL version"
```

```
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Error: couldn't find RGB GLX visual or fbconfig

```

**Comment by thigitogatiamas** [comment]
Also when I run the code without the `glEnable()` stuff above I get:

```
    self.ctx = moderngl.create_standalone_context(backend='EGL')
  File "/usr/local/lib/python3.5/dist-packages/moderngl/__init__.py", line 3121, in create_standalone_context
    ctx.mglo, ctx.version_code = mgl.create_standalone_context(settings)
mgl.Error: cannot detect EGL display
```

**Comment by cprogrammer1994** [comment]
I think you have some driver issues if none of the backends manage to detect the display.

**Comment by thigitogatiamas** [comment]
Well for the EGL I did not use Xvfb? So there is not display? But what do you mean by driver issues? I have got the latest NVIDIA drivers and nvidia-smi works fine. I think it is rather some config issues regarding the x-server?

**Comment by cprogrammer1994** [comment]
I don't know how EGL works, but I can tell for sure that `mgl.Error: cannot detect EGL display` means that `eglGetDisplay(EGL_DEFAULT_DISPLAY)` returned `EGL_NO_DISPLAY`

**Comment by thigitogatiamas** [comment]
Meaning? I know there is no display, because it is running on a server. And I was trying to simulate a "display" using Xvfb! So what do I do to not get that error?

**Comment by thigitogatiamas** [comment]
Okay so I went to the server and compiled and started following code:

 ```
 #include <EGL/egl.h>
  static const EGLint configAttribs[] = {
          EGL_SURFACE_TYPE, EGL_PBUFFER_BIT,
          EGL_BLUE_SIZE, 8,
          EGL_GREEN_SIZE, 8,
          EGL_RED_SIZE, 8,
          EGL_DEPTH_SIZE, 8,
          EGL_RENDERABLE_TYPE, EGL_OPENGL_BIT,
          EGL_NONE
  };    

  static const int pbufferWidth = 9;
  static const int pbufferHeight = 9;

  static const EGLint pbufferAttribs[] = {
        EGL_WIDTH, pbufferWidth,
        EGL_HEIGHT, pbufferHeight,
        EGL_NONE,
  };

int main(int argc, char *argv[])
{
  // 1. Initialize EGL
  EGLDisplay eglDpy = eglGetDisplay(EGL_DEFAULT_DISPLAY);

  EGLint major, minor;

  eglInitialize(eglDpy, &major, &minor);

  // 2. Select an appropriate configuration
  EGLint numConfigs;
  EGLConfig eglCfg;

  eglChooseConfig(eglDpy, configAttribs, &eglCfg, 1, &numConfigs);

  // 3. Create a surface
  EGLSurface eglSurf = eglCreatePbufferSurface(eglDpy, eglCfg, 
                                               pbufferAttribs);

  // 4. Bind the API
  eglBindAPI(EGL_OPENGL_API);

  // 5. Create a context and make it current
  EGLContext eglCtx = eglCreateContext(eglDpy, eglCfg, EGL_NO_CONTEXT, 
                                       NULL);

  eglMakeCurrent(eglDpy, eglSurf, eglSurf, eglCtx);

  // from now on use your OpenGL context

  // 6. Terminate EGL when finished
  eglTerminate(eglDpy);
  return 0;
}
```

```
g++ -o test test.cpp -lEGL

./test
```
I do not get an error from that, so it seems like `EGL` is working? Are you sure there is nothing wrong with your code?

**Comment by thigitogatiamas** [comment]
Could it be a problem that I have to add anything to `LD_LIBRARY_PATH` or anything else that needs to be configured apart from the driver? My driver installation seems fine? I would not know what there can be so complicated that it does not work?

**Comment by thigitogatiamas** [comment]
> All you have to do is to install this version and call create_standalone_context(backend='EGL')
> If the call succeed please try to print the OpenGL version. If the version is above 3.3 I will restore the EGL support form ModernGL
> 
> If you manage to print the OpenGL version without ModernGL and the version is above to 3.3. It is possible that I will be able to make ModernGL work there.

On my local computer it works with OpenGL 4. (Printed OpenGL version without ModernGL). I do not know how to print the OpenGL version with ModernGL though.

**Comment by thigitogatiamas** [comment]
Okay I think I have finally figured it out:

In your [code](https://github.com/cprogrammer1994/ModernGL/blob/5.0.4/src/GLContext.cpp#L768) you call:
`eglGetDisplay(0)` 
rather than 
`eglGetDisplay(EGL_DEFAULT_DISPLAY)`

So you basically "hard-coded" the `display_id`, hence it could not find the id on my server I suppose. Could you alter your code so that it will work for others as well?

Have a look at this example here (Multi-GPU)

```
#include <assert.h>
#include <EGL/egl.h>
#include <stdio.h>
#include <iostream>

#define EGL_EGLEXT_PROTOTYPES
#include <EGL/egl.h>
#include <EGL/eglext.h>

static const EGLint configAttribs[] = {
          EGL_SURFACE_TYPE, EGL_PBUFFER_BIT,
          EGL_BLUE_SIZE, 8,
          EGL_GREEN_SIZE, 8,
          EGL_RED_SIZE, 8,
          EGL_DEPTH_SIZE, 8,
          EGL_RENDERABLE_TYPE, EGL_OPENGL_BIT,
          EGL_NONE
  };

  static const int pbufferWidth = 9;
  static const int pbufferHeight = 9;

  static const EGLint pbufferAttribs[] = {
        EGL_WIDTH, pbufferWidth,
        EGL_HEIGHT, pbufferHeight,
        EGL_NONE,
  };

int main(int argc, char *argv[])
{

    static const int MAX_DEVICES = 4;
    EGLDeviceEXT eglDevs[MAX_DEVICES];
    EGLint numDevices;

    PFNEGLQUERYDEVICESEXTPROC eglQueryDevicesEXT =(PFNEGLQUERYDEVICESEXTPROC)
    eglGetProcAddress("eglQueryDevicesEXT");

    eglQueryDevicesEXT(MAX_DEVICES, eglDevs, &numDevices);

    printf("Detected %d devices\n", numDevices);

    PFNEGLGETPLATFORMDISPLAYEXTPROC eglGetPlatformDisplayEXT =  (PFNEGLGETPLATFORMDISPLAYEXTPROC)
    eglGetProcAddress("eglGetPlatformDisplayEXT");

    EGLDisplay eglDpy = eglGetPlatformDisplayEXT(EGL_PLATFORM_DEVICE_EXT, eglDevs[0], 0); (--> multi gpu)

    //EGLDisplay eglDpy = eglGetDisplay(EGL_DEFAULT_DISPLAY); --> for one display (single gpu)


    // 1. Initialize EGL
    std::cout << "EGL eglDpy: " << eglDpy << std::endl;

    EGLint major, minor;

    eglInitialize(eglDpy, &major, &minor);

    std::cout << "minor, major: " << minor << ", " << major << std::endl;


    // 2. Select an appropriate configuration
    EGLint numConfigs;
    EGLConfig eglCfg;

    eglChooseConfig(eglDpy, configAttribs, &eglCfg, 1, &numConfigs);
    std::cout << "EGL numConfigs: " << numConfigs << std::endl;
    std::cout << "EGL eglCfg: " << eglCfg << std::endl;


    // 3. Create a surface
    //EGLSurface eglSurf = eglCreatePbufferSurface(eglDpy, eglCfg, pbufferAttribs);
    //std::cout << "EGL surf: " << eglSurf << std::endl;

    // 4. Bind the API
    eglBindAPI(EGL_OPENGL_API);

    // 5. Create a context and make it current
    EGLContext eglCtx = eglCreateContext(eglDpy, eglCfg, EGL_NO_CONTEXT,NULL);

    assert (eglDpy != NULL);
    assert (eglCfg != NULL);
    //assert (eglSurf != NULL);

    eglMakeCurrent(eglDpy, EGL_NO_SURFACE, EGL_NO_SURFACE, eglCtx);

    std::cout << "EGL Ctx: " << eglCtx << std::endl;
    assert (eglCtx != NULL);

    // 6. Terminate EGL when finished
    eglTerminate(eglDpy);
    return 0;
}
```
Maybe you could change it in a way that one can "decide" which GPU to use depenent on `eglDevs`.

PS: I have run the code given above on the server without any issues, so I am 100% sure there are no driver issues!

**Comment by cprogrammer1994** [comment]
```
python -m moderngl
```

or

```
ctx = moderngl.create_standalone_context()
print(ctx.version_code)
```

- for OpenGL 4.5 the version_code will be 450
- for OpenGL 3.3 the version_code will be 330
- for OpenGL 2.x the version_code will be 0
