### ISSUE TITLE
VAO index array hardcoded to UNSIGNED_INT

### ISSUE THREAD

**Issue by einarf** [cprogrammer1994/ModernGL#193]
It could be useful if `UNSIGNED_SHORT` was also supported as it makes scene loading from for example gltf a lot more convenient. Might be something I'll take a stab at.

https://github.com/cprogrammer1994/ModernGL/blob/e480d5d37c5015e2f11daf9c5a81fe7ac1803c5a/src/VertexArray.cpp#L263

**Comment by cprogrammer1994** [comment]
Hi!

I think ModernGL should support `GL_UNSIGNED_SHORT` index values.

Implementation:

Vertex arrays should have a property.
This property should be an int.
Accepted values are 1, 2 and 4 (bytes, shorts and ints)
The default value should be 4.

I don't know how should we name this property.

Thanks!

**Comment by einarf** [comment]
Pretty close to what I was thinking about as well.

`simple_vertex_array` and `vertex_array` should then have an additional parameter (default: 4)
Name could be `index_element_size`.

I guess this means supporting `GL_UNSIGNED_BYTE`, `GL_UNSIGNED_SHORT`, or `GL_UNSIGNED_INT`.

**Comment by einarf** [comment]
FYI: Working on this now
