### ISSUE TITLE
Possible to adjust Depth Range?

### ISSUE THREAD

**Issue by michael-iuzzolino** [cprogrammer1994/ModernGL#196]
### Issue / Question / Feature request
I'm wondering if it's possible to adjust the depth range. Is this feature available? I suspect that is contributing to this odd rendering issue I'm facing:

![image](https://user-images.githubusercontent.com/21148987/41895504-0e78c4d4-78d7-11e8-809c-ef5b4a065173.png)

DEPTH_TEST is enabled via `render_ctx.enable(ModernGL.DEPTH_TEST)`, and I've mapped the norms to the RGB channels and the surface norms shouldn't be discontinuous like this (should look more like the image below); these models apparently have internal rendering geometry (e.g., the cabin is modeled with seats, overhead luggage compartments, etc.). We suspect it may be due to these internal points with the external points being too close given whatever default values, and think it may be fixed with adjusting the depth range. We've tested the normals with other software and they all checkout, but when we render in ModernGL we get a lot of renders like the one above. However, I'm completely new to graphics and could be very wrong about this. Any thoughts?

![image](https://user-images.githubusercontent.com/21148987/41895911-0d0b203c-78d8-11e8-8200-c91d20561aa0.png)

Greatly appreciate all of your efforts for this awesome library. :)

### Version info
ModernGL: 4.2.2 (installed)
Vendor: Intel
Renderer: Intel(R) Iris(TM) Plus Graphics 640
Version: 4.5.0 - Build 22.20.16.4749
Python: 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Platform: win32

**Comment by einarf** [comment]
Not sure about the details for the depth buffer specifically.

You can possibly solve this by adjusting your near and far values in your projection.
- Use at least a near value of 1.0 (not lower)
- Narrow down the far value as much a possible

**Comment by cprogrammer1994** [comment]
Hi!

I see that you are using ModernGL 4.x

As I remember there is no option to set the depth range but it can be added with a minimal touch to the source. I believe the "depth fighting" on the first image is cased my an 8bit depth buffer.

Are you rendering to a window or to a framebuffer?

In case you render to a window you will need to configure the window to create a 24 bit depthbuffer at least. For example format can be set for PyQt5 to:

```py
        fmt = QtOpenGL.QGLFormat()
        fmt.setVersion(3, 3)
        fmt.setProfile(QtOpenGL.QGLFormat.CoreProfile)
        fmt.setSwapInterval(1)
        fmt.setSampleBuffers(True)
        fmt.setDepthBufferSize(24)  # <-- this
```

If you render to a framebuffer you will need create a `depth_renderbuffer` with `floats=True` (in ModernGL4.x)

If you render to a framebuffer and you have no depth_renderbuffer added depth testing will not work at all.

**Comment by michael-iuzzolino** [comment]
@einarf and @cprogrammer1994, thank you so much for the feedback! 

I am rendering to a framebuffer, and the `depth_renderbuffer` with float=True did the trick!

**Comment by cppietime** [comment]
> In case you render to a window you will need to configure the window to create a 24 bit depthbuffer at least. For example format can be set for PyQt5 to:
> 
> ```python
>         fmt = QtOpenGL.QGLFormat()
>         fmt.setVersion(3, 3)
>         fmt.setProfile(QtOpenGL.QGLFormat.CoreProfile)
>         fmt.setSwapInterval(1)
>         fmt.setSampleBuffers(True)
>         fmt.setDepthBufferSize(24)  # <-- this
> ```

Is this specifically for when you're using PyQt5 for your window? Is there a way to do this in a pygame window?

**Comment by einarf** [comment]
> Is this specifically for when you're using PyQt5 for your window? Is there a way to do this in a pygame window?

For pygame see : https://github.com/moderngl/moderngl-window/blob/0fe2b5472153a567ed24dae304735ff8ded67322/moderngl_window/context/pygame2/window.py#L30-L55
