### ISSUE TITLE
Sampler object support

### ISSUE THREAD

**Issue by einarf** [cprogrammer1994/ModernGL#198]
### Feature request

One very useful feature we are missing is sampler objects. It's so much easier to control texture parameters and they are also pretty much required for gltf scenes.

I might take a stab at this some time in the future. It's really just an object you bind with `glBindSampler(location, sampler_id)`, so it might not even need to include any C code at all.

`glSamplerParameter*`, `MAX_TEXTURE_MAX_ANISOTROPY`, `TEXTURE_MAX_ANISOTROPY` are on the short list of fuctions/attribs needed.

#### Possible Implementation

- `Sampler` python class storing each sampler parameter
- `sampler = Context.sampler(<sampler parameter) -> Sampler`
- `sampler.use(location=0)`

Wost case this approach can always be changed to a version with C code in the future without breaking compatibility. Might not be a good idea to expose `glSamplerParameter*` on the python side.

If this sounds like a good idea, I can jump on pretty fast.
(sampler object is GL 3.2+)

### Version info

5.2.1

**Comment by einarf** [comment]
Been playing around with samplers a bit locally. There was actually one case I had to use samplers to read the depth texture with `sampler2D` because the `Context.depth_texture` function is currently hard coding in texture compare mode.

**Comment by cprogrammer1994** [comment]
are you sure? the compare function was added earlier. not sure when

**Comment by einarf** [comment]
As far as I know, you can't change `GL_TEXTURE_COMPARE_MODE`, so It doesn't matter if you can  change `GL_TEXTURE_COMPARE_FUNC`.

**Comment by einarf** [comment]
`MGLTexture_set_compare_func` could for example be set to `None` to disable it.
Optionally a separate `MGLTexture_set_compare_mode` with a boolean parameter setting `GL_COMPARE_REF_TO_TEXTURE` if True and `GL_NONE` if False.

**Comment by cprogrammer1994** [comment]
exposing `GL_TEXTURE_COMPARE_MODE` is a good idea.

I would go with the first suggestion. Will all the valid settings be covered?

**Comment by cprogrammer1994** [comment]
@einarf I think we could try to add Sampler object support in the next release. If this requires too much time then we will postpone it. What do you think? How can I help?

**Comment by einarf** [comment]
I'll see what I can do today. It's the last remaining feature that requires me to use PyOpenGL, so the motivation is definitely there.

**Comment by einarf** [comment]
As a side note: I see a lot of missing entries exposing getters/setters for things like ``max_samples``, ``max_integer_samples``, ``max_texture_units``, ``default_texture_unit``. I was adding a ``max_anisotropy`` attribute and got a bit confused. All these missing attributes are also in the docs, so I assume they need to be added. I can fix that in my PR as well while I'm at it.

https://github.com/cprogrammer1994/ModernGL/blob/c67149a53cfde14e0a045d9f8d05c7952fee12b0/src/Context.cpp#L1212-L1230

**Comment by cprogrammer1994** [comment]
merged #215
