### ISSUE TITLE
Break up __init__.py

### ISSUE THREAD

**Issue by NeilGirdhar** [cprogrammer1994/ModernGL#200]
`moderngl.__init__.py` contains all of the source.  It should be broken down into modules.  These modules should specify an `__all__` of whatever needs to be exported, and then `__init__.py` should `import *` from each of them.

**Comment by cprogrammer1994** [comment]
Circluar imports were inconvinient in past versions of Python. Not sure if we break it up again we can keep older versions of python supported. I dont like having all the wrapper in a big big file too.

**Comment by cprogrammer1994** [comment]
#206 was merged. Thanks!
