### ISSUE TITLE
Rewrite "two part" initializations

### ISSUE THREAD

**Issue by NeilGirdhar** [cprogrammer1994/ModernGL#201]
This style is not Pythonic:

```
res = Program.__new__(Program)
res.mglo, ls1, ls2, ls3, ls4, ls5, res._subroutines, res._geom, res._glo = self.mglo.program(
```

Don't just call `__new__` and then do the initialization outside `__init__`.  Instead, pass the context into `Program`'s constructor.  This would allow people to inherit from `Program`.

**Comment by einarf** [comment]
As far as I know this was done to make it hard for the users to instantiate their own objects with ``Program()``. They are supposed to use the methods in the ``Context`` class to create instances.

**Comment by NeilGirdhar** [comment]
@einarf I like the library design, which is why I'm in the process of porting my code over and I will soon propose folding in my https://github.com/NeilGirdhar/glx/tree/master/glx library after I've ported it.

However, I don't agree with "making things difficult for the user" by writing obfuscated code.  Anyway, adding all of the necessary members as parameters of the constructor would make it _harder_ for the user to accidentally instantiate `Program`.

**Comment by NeilGirdhar** [comment]
Actually, on second look, it would be better to pass the context into `Program`'s constructor.  That would allow people to inherit from `Program`.

**Comment by cprogrammer1994** [comment]
ModernGL classes are considered "final". Their C++ implementation properly set this flag. Due to the python wrapper (that makes  methods "lintable") you are able to subclass  those classes.

None of the internal method will accept a subclass of Program. If they were accepting subclasses they would have an overhead to do that.

One of my prototypes allow me to check for internal types and use their slots a way faster then it was implemented in pure python.

The implementation is not a "beautiful code" I have to admit. The use of moderngl should be pythonic, readable, and easy to understand.

To have a subclass you should implement a class with an attribute holding a ref to a moderngl.Program. you will nees a wrapper over classes that accept a program in their methods.

**Comment by cprogrammer1994** [comment]
The impl should be more lightweight. It is hard for new contributors to push to this repo. I am thinking on it how could I change stuff to make things easier without havint too much performance loss

**Comment by einarf** [comment]
I guess it just means you have to go the composition route when extending classes. That's what I currently do. The obvious downside is that you have to wrap all the methods, but that's not a huge issue for me personally. Performance is pri 1 for me.

**Comment by NeilGirdhar** [comment]
> None of the internal method will accept a subclass of Program. If they were accepting subclasses they would have an overhead to do that.

I don't see why there's necessarily any overhead.

> To have a subclass you should implement a class with an attribute holding a ref to a moderngl.Program. you will nees a wrapper over classes that accept a program in their methods.

You're saying to use [“composition over inheritance”](https://en.wikipedia.org/wiki/Composition_over_inheritance).  You're right in most cases, I agree.

**Comment by cprogrammer1994** [comment]
>>None of the internal method will accept a subclass of Program. If they were accepting subclasses they would have an overhead to do that.

> I don't see why there's necessarily any overhead.

Using `PyObject_IsInstance` over a `pointer == test` would have an impact on performance. For types except (int, float, str, dict ...) an isinstance check is more then just a `==` in c++.

**Comment by NeilGirdhar** [comment]
I don't see why inheritance would be especially expensive, but even if it is, it's not something that you should try to prevent.  It's the user's decision.

**Comment by cprogrammer1994** [comment]
On the master the framebuffer have a check on its attachments when created:

```c++
if (Py_TYPE(item) == &MGLTexture_Type) {
```

When a VertexArray is created, the args are unpacked as follows:

```c++
MGLProgram * program;
...

int args_ok = PyArg_ParseTuple(
	args,
	"O!OOIp",
	&MGLProgram_Type,
	&program,
...
);
```

but these are not that important.

The main reason I don't want to allow subclasses is that on the experimental branch I was able to access the wrapper class slots from C++ without a lookup cost (time). I am also able wrapping objects and return them directly from C++.

**Comment by NeilGirdhar** [comment]
> I was able to access the wrapper class slots from C++ without a lookup cost (time). I am also able wrapping objects and return them directly from C++.

Fair enough, I'm not going to question your design.

If you want to prevent subclassing, I think a nicer way to do that is:
```
class SomeBase:

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        if cls is not SomeBase:
            raise TypeError


class Derived(SomeBase):
    pass
```
This raises a `TypeError` on declaration rather than what is currently implemented, which waits for the derived class to call the superclass's `__init__`, which it may not even do.

**Comment by NeilGirdhar** [comment]
How opposed are you to something like this?
```
class Buffer:
    '''
        Buffer objects are OpenGL objects that store an array of unformatted memory
        allocated by the OpenGL context, (data allocated on the GPU).
        These can be used to store vertex data, pixel data retrieved from images
        or the framebuffer, and a variety of other things.

        A Buffer object cannot be instantiated directly, it requires a context.
        Use :py:meth:`Context.buffer` to create one.

        Copy buffer content using :py:meth:`Context.copy_buffer`.
    '''

    __slots__ = ['mglo', '_size', '_dynamic', '_glo', 'ctx', 'extra']

    def __init__(self, context, data=None, *, reserve=0, dynamic=False):
        '''
            Create a :py:class:`Buffer` object.

            Args:
                context: the Context.
                data (bytes): Content of the new buffer.

            Keyword Args:
                reserve (int): The number of bytes to reserve.
                dynamic (bool): Treat buffer as dynamic.

            Returns:
                :py:class:`Buffer` object
        '''

        if type(reserve) is str:
            reserve = mgl.strsize(reserve)

        self.mglo, self._size, self._glo = context.mglo.buffer(data, reserve, dynamic)
        self._dynamic = dynamic
        self.ctx = context
        self.extra = None
        if type(self) is not Buffer:
            raise TypeError("Buffer does not support subclassing.  Use composition instead.")
```
You could still keep `Context.buffer`:
```
    def buffer(self, data=None, *, reserve=0, dynamic=False) -> Buffer:
        '''
            Create a :py:class:`Buffer` object.

            Args:
                data (bytes): Content of the new buffer.

            Keyword Args:
                reserve (int): The number of bytes to reserve.
                dynamic (bool): Treat buffer as dynamic.

            Returns:
                :py:class:`Buffer` object
        '''
        return Buffer(self, data, reserve=reserve, dynamic=dynamic)
```

**Comment by cprogrammer1994** [comment]
The upcomming major version will have better initalization for the wrapper.
