### ISSUE TITLE
Replace use and release with context managers

### ISSUE THREAD

**Issue by NeilGirdhar** [cprogrammer1994/ModernGL#202]
There is a nicer way in Python to do this:

```
    def use(self, location=0) -> None:
        '''
            Bind the texture.
            Args:
                location (int): The texture location.
                    Same as the integer value that is used for sampler2D
                    uniforms in the shaders. The value ``0`` will bind the
                    texture to the ``GL_TEXTURE0`` binding point.
        '''

        self.mglo.use(location)

    def release(self) -> None:
        '''
            Release the ModernGL object.
        '''

        self.mglo.release()
```

Instead, do this:

```
    @contextmanager
    def use(self, location=0):
        '''
            Bind the texture.
            Args:
                location (int): The texture location.
                    Same as the integer value that is used for sampler2D
                    uniforms in the shaders. The value ``0`` will bind the
                    texture to the ``GL_TEXTURE0`` binding point.
        '''

        self.mglo.use(location)
        try:
            yield
        finally:
            self.mglo.release()
```

This guarantees that the resource is released, and uses Python's block structure reflect the bracketing pattern.

**Comment by NeilGirdhar** [comment]
(Sorry for the many issues, but I'd like to contribute to this project soon and it's less exciting if there are design flaws.)

**Comment by cprogrammer1994** [comment]
Hi! The release will call a glDelete... there is no method that would be the inverse of a use().

**Comment by cprogrammer1994** [comment]
To have a with statement please take a look at the Scope object

**Comment by NeilGirdhar** [comment]
Okay, I understand!  I guess, you might want to call `release` from `__del__`, but it's not a big deal.

**Comment by einarf** [comment]
Yup. That extra ``glUseProgram`` can have devastating effects on performance. Also in opengl core 3.3+ contexts it doesn't make sense to unbind anything. You can't really draw anything without a shader anyway. 😃

**Comment by cprogrammer1994** [comment]
> I guess, you might want to call release from \_\_del\_\_, but it's not a big deal.

No, please see [this](https://www.khronos.org/opengl/wiki/Common_Mistakes#The_Object_Oriented_Language_Problem) link.

**Comment by NeilGirdhar** [comment]
You're worried that the OpenGL context might be dead when `__del__` is finally called.  That's fair.  If you want to guarantee lifetimes in Python (the way you do in C++), then you would have to use context managers.

**Comment by cprogrammer1994** [comment]
With my custom window implementation, closing the window will result in a destroyed OpenGL context. the `__del__` of the moderngl classes will be called only after this event.

**Comment by NeilGirdhar** [comment]
> the `__del__` of the moderngl classes will be called only after this event.

—not necessarily.  `__del__` might be called as soon as the no references remain to an object, but I agree that `__del__` _might_ be called after the context is destroyed.

Anyway, if creation and release follows a bracketing pattern for some objects, then they should be written as context managers.
