### ISSUE TITLE
Add font support

### ISSUE THREAD

**Issue by NeilGirdhar** [cprogrammer1994/ModernGL#203]
I would like to merge my [font rendering library](https://github.com/NeilGirdhar/glx/tree/master/glx/font) that

- renders a font into a giant texture (a "font atlas"),
- renders the kerning information into a second texture
- turns any string of length n into a 1xn texture
- uses a shader program that accepts the three textures and renders fully kerned text in OpenGL

**Comment by cprogrammer1994** [comment]
I would prefer to have this as a separate module. Currently we have obj file support in a module called `objloader`. What do you think?

**Comment by NeilGirdhar** [comment]
Sure, it's up to you!  I'll leave it in glx, and hopefully port it from PyOpenGL to ModernGL soon.

**Comment by einarf** [comment]
Just as a side note: We could make an md file with links to packages using moderngl to make them easier to find.

**Comment by cprogrammer1994** [comment]
sure! We can also link it in the README.md.

Should we add this list directly to the README.md?

**Comment by einarf** [comment]
Sure. Can just make a section in README somewhere so people can add their libraries. If needed later it can always be moved. The library owners should just add the links themselves I guess.
