### ISSUE TITLE
Use fixtures instead of unittest set up and tear down methods

### ISSUE THREAD

**Issue by NeilGirdhar** [cprogrammer1994/ModernGL#205]
This style is the antiquated unittest style:
```
class TestBuffer(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.ctx = get_context()

    def test_buffer_clear_1(self):
        buf = self.ctx.buffer(data=b'\xAA\x55' * 10)
        buf.clear(chunk=b'AB')
        self.assertEqual(buf.read(), b'AB' * 10)
```
Use `pytest` fixtures and global functions instead:
```
@pytest.fixture(scope='module')
def ctx():
    return get_context()


def test_buffer_clear_1(ctx):
    buf = ctx.buffer(data=b'\xAA\x55' * 10)
    buf.clear(chunk=b'AB')
    assert buf.read() == b'AB' * 10  # pytest does magic with this kind of assertion
```

In the case of the context, you can put the fixture into `conftest.py` and have its scope be `session` so that it's shared between all tests.  This replaces `get_context` in `common.py`.

**Comment by cprogrammer1994** [comment]
I will try this out. Your code looks simpler, more readable.

**Comment by cprogrammer1994** [comment]
How can I get assert almost equal work?

**Comment by cprogrammer1994** [comment]
`numpy.testing` seems to be fine if there are no alternatives. We depend on `numpy` in the tests anyway.

**Comment by NeilGirdhar** [comment]
You can use [`pytest.approx`](https://docs.pytest.org/en/latest/reference.html#pytest-approx), or `numpy.testing` depending on your taste.

**Comment by cprogrammer1994** [comment]
I will not refactor the tests now. But for new tests I will consider using this approach.
Thanks for the suggestion 😄
