### ISSUE TITLE
Expose glVertexAttribPointer

### ISSUE THREAD

**Issue by NeilGirdhar** [cprogrammer1994/ModernGL#211]
We can discuss how moderngl should do expose glVertexAttribPointer here.

In my library, I created a [`BoundAttribute`](https://github.com/NeilGirdhar/glx/blob/master/glx/shader_program/bound_attribute.py) object that has a `bind` method to make this OpenGL call.  The idea is that you create buffer descriptions like this:
```
            self.buffer, = gl.glGenBuffers(1)

            # Create one vertex array and describe it.
            # The array is fed using a numpy array of shape (n, 2), which
            # describes n (x, y) pairs.
            self.vertex_array, = self.create_vertex_arrays(
                [BufferDescription(
                    self.buffer,
                    np.dtype(('f', (2,))),
                    [Attribute('vertex', [], is_vector=True)])])
```
The first line is `moderngl.Context.buffer(...`.  The rest binds all of the attributes that it can to a vertex array.  Then the next time (e.g. at draw time) the vertex array is bound, all the attributes don't need to be rebound.

**Comment by cprogrammer1994** [comment]
`glVertexAttribPointer` is exposed by `vao.bind`.
They are not used in the examples, but you can find some tests.
