### ISSUE TITLE
GL Error when clearing default framebuffer

### ISSUE THREAD

**Issue by einarf** [cprogrammer1994/ModernGL#212]
When clearing the default framebuffer a GL error triggers (GL_INVALID_ENUM) when ``DrawBuffers`` is called. I'm guessing we can't use ``DrawBuffers`` on the default framebuffer and should probably detect this in some way. I haven't looked at the code too closely, but `framebuffer_obj` is `0`, so a quick fix could be only calling it when framebuffer_obj > 0.

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDrawBuffers.xhtml
> GL_INVALID_ENUM is generated if the API call refers to the default framebuffer and one or more of the values in bufs is one of the GL_COLOR_ATTACHMENTn tokens.

https://github.com/cprogrammer1994/ModernGL/blob/c67149a53cfde14e0a045d9f8d05c7952fee12b0/src/Framebuffer.cpp#L378-L390

**Comment by NeilGirdhar** [comment]
If you're using PyQt, are you sure you have the right framebuffer?  I was noticing that calling `detect_framebuffer` was giving me the wrong result when called from `initializeGL`.  I had to call it from `paintGL`.

**Comment by einarf** [comment]
I'm using GLFW and I get framebuffer 0 as the screen framebuffer, so that part looks correct.
