### ISSUE TITLE
Compute Shader Uniform __getitem__ missing?

### ISSUE THREAD

**Issue by pocdn** [cprogrammer1994/ModernGL#217]
For ctx.program there is a convenience method to set/get uniforms as
 mvp = self.prog['Mvp']. This is a rather nice API for working with uniforms. in vertex, fragment, etc shaders. 

The compute shader API acts differently. Is there a way  to similarly work with uniforms in the ctx.compute_shader? For example, the following runs without error

>     self.computeprog = self.ctx.compute_shader(
>             source='''
>                 #version 430
>                  
>                 layout(local_size_x=16, local_size_y = 16, local_size_z = 1) in;
>                  
>                 layout(rg32f, binding=0) readonly uniform image2D grid_in;
>                 layout(rg32f, binding=1) writeonly uniform image2D grid_out;
>                  
>                 uniform int N;
>                 uniform int Ns;
>                 uniform int dir;
>                  
>                 const float pi = 3.141592653589793;
>                  
>                 vec2 cmul(vec2 a, vec2 b)
>                 {
>                     return vec2(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x);
>                 }
>                  
>                 void main()
>                 {
>                     ivec2 ij = ivec2(gl_GlobalInvocationID.xy);
>                     int i = ij.x;
>                     int j = ij.y;
>                     int k = Ns / 2;
>                     int a = (i / Ns) * k;
>                     int b = i % k;
>                     int i0 = a + b;
>                     int i1 = i0 + (N / 2);
>                     float t = 2*pi*i/Ns;
>                     vec2 f = vec2(cos(t), sin(t));
>                     f.y *= dir;
>                     vec2 x0 = imageLoad(grid_in, ivec2(i0, j)).xy;
>                     vec2 x1 = imageLoad(grid_in, ivec2(i1, j)).xy;
>                     imageStore(grid_out, ij, vec4(x0 + cmul(f, x1), 0, 0));
>                 }
>             ''')

but setting/getting uniforms like the following 

> self.u_dir = self.computeprog['dir']
> etc

fails with

> TypeError: 'ComputeShader' object is not subscriptable

**Comment by cprogrammer1994** [comment]
Hi!

Most of it is implemented. Unfortunately the last step to return the uniforms, uniform blocks, ... is missing. The changes in the python layer would be minimal. it must work similar to the Program object.

https://github.com/cprogrammer1994/ModernGL/blob/e04d3e2541e3dc3b117571d5f57b7d77502ab4c5/src/ComputeShader.cpp#L225

https://github.com/cprogrammer1994/ModernGL/blob/e04d3e2541e3dc3b117571d5f57b7d77502ab4c5/src/Program.cpp#L593

I think it is easy to fix.

**Comment by cprogrammer1994** [comment]
You can test the fix:

```
python -m pip install https://github.com/cprogrammer1994/ModernGL/archive/fix-compute-shader-uniforms.zip
```

This will hopefully be merged at the end of this week.

**Comment by cprogrammer1994** [comment]
Thank you for reporting this issue! The fix will be available in the next release.

**Comment by pocdn** [comment]
Thank you. Great!
