### ISSUE TITLE
Support different texture wrap modes (future)

### ISSUE THREAD

**Issue by einarf** [cprogrammer1994/ModernGL#224]
Something to consider in the future:

Currently we have ``repeat_x``, ``repeat_y`` etc. for setting texture wrap. This means we are only really supporting ``GL_REPEAT`` and ``GL_CLAMP_TO_EDGE``.

.. but we do have other wrap options:
```
GL_MIRRORED_REPEAT
GL_MIRROR_CLAMP_TO_EDGE
GL_CLAMP_TO_BORDER
```

Border color is currently supported when setting ``border_color`` in a sampler, but this overrides the ``repeat`` values making things pretty weird.

I suggest exposing ``wrap_x/y/z`` instead so the values can be set more freely.

```
wrap_x = moderngl.REPEAT
wrap_x = moderngl.CLAMP_TO_EDGE
wrap_x = moderngl.MIRRORED_REPEAT
wrap_x = moderngl.MIRROR_CLAMP_TO_EDGE
wrap_x = moderngl.GL_CLAMP_TO_BORDER
```

Noticed this as well in some GLTF scenes looking weird since they are supporting ``MIRRORED_REPEAT``:
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/sampler.schema.json

**Comment by einarf** [comment]
I'll be willing to do this for 6.0

**Comment by einarf** [comment]
Is there anything that stops me from starting on this one?

I think the new properties should be called ``wrap_x``, ``wrap_y``, and ``wrap_z``. Optionally conform to the ``u, v, s`` suffixes. By also properly documenting the valid wrap enum values I think this should still be fairly straight forward to use.

**Comment by cprogrammer1994** [comment]
@cprogrammer1994

**Comment by cprogrammer1994** [comment]
https://github.com/cprogrammer1994/ModernGL/pull/286

**Comment by einarf** [comment]
Very nice 👍

**Comment by cprogrammer1994** [comment]
it should work now with next, closing...

**Comment by Aspect26** [comment]
is there any workaround for this in 5.5 ?

**Comment by einarf** [comment]
Samplers do add border color at least. Changing wrapping is such a huge breaking change in 5.5 I don't really see any nice way of supporting it there. It could be done with new properties..
