### ISSUE TITLE
Sampler Binding

### ISSUE THREAD

**Issue by einarf** [cprogrammer1994/ModernGL#227]
What do you think about having the sampler as an optional parameter to ``Texture.use(...)``?

Currently:
```python
sampler.use(location=0)
texture.use(location=0)
```

Sampler parameter:
```python
texture.use(location=0, sampler=sampler)
```

It may give the impression that a sampler belongs to the bound texture and not the texture unit as a whole? .. or we assume people know the sampler will stick to the unit?

@cprogrammer1994 response:

Is it common to create a few samplers and use with multiple textures?
What do you think, should samplers be created like vao's? (Vaos store a program object. When you call vao.render it will bind the program object that vao internally knows. Sampler.use could bind the texture to a texture unit)
I think it could be more convenient to have samplers as the only option to bind a texture to a texture unit (in the next major). Textures would store the texture's data only. Samplers would be responsible for handling the sampler parameters and binding the texture to its unit when requested.
This could ensure not to have invalid sampler, texture pairs bound.
This could also ensure that build_mipmaps cannot affect the filter parameters.
This would force the user to create similar samplers for different textures.

**Comment by einarf** [comment]
I will have to think about this a bit more, but it doesn't sound bad if the goal is the ensure samplers do not mess up for the user.

```python
# Create sampler for a texture
sampler = ctx.sampler(texture, ... sampler params ...)

# Bind the sampler and texture
sampler.use(location=N)
```

An advantage is also that we can check the texture type and properties to ensure no invalid sampler parameters are set causing incompleteness issues. https://www.khronos.org/opengl/wiki/Texture#Texture_completeness

```python
# Would not be allowed if the texture don't have mimpaps
sampler = ctx.sampler(texture, filter=(moderngl.LINEAR_MIPMAP_LINEAR, moderngl.LINEAR)))

# Allowed
texture.build_mipmaps()
sampler = ctx.sampler(texture, filter=(moderngl.LINEAR_MIPMAP_LINEAR, moderngl.LINEAR))
```

I would at least make the texture property (no setter) available from the sampler instance since passing around two instances is quite the burden.

```python
sampler = ctx.sampler(texture, ... params ...)
sampler.texture.build_mipmaps()
sampler.filter = (moderngl.LINEAR_MIPMAP_LINEAR, moderngl.LINEAR)
```

This also means we can remove all the sampler parameters from the texture classes.

**Comment by cprogrammer1994** [comment]
It is hard for me to make a decision on this `texture.use(location=0, sampler=sampler)` call.

using texture at location 0 with sampler is clearly understandable.
sampler=None would mean to unset the sampler.
sampler.use will not be needed in that case.
this would break the original idea:

```py
sampler.use()
texture.use() # the default parameters would be location=0, sampler=None
```

**Comment by cprogrammer1994** [comment]
I think you can freely decide to add or not to add this parameter to `texture.use`. I personally prefer to try them out and base the final decision on them later.

**Comment by einarf** [comment]
I think just keeping them separate for now is fine. Then we can play with them more and see what makes more sense.

**Comment by einarf** [comment]
After some more pondering..

We should not forget that this is an important use case for samplers:
```py
sampler_repeat = ctx.sampler(repeat_x=True, repeat_y=True)
sampler_no_repeat = ctx.sampler(repeat_x=False, repeat_y=False)
texture = ctx.texture(...)

sampler_repeat.use(location=0)
texture.bind(location=0)

sampler_no_repeat.use(location=1)
texture.bind(location=1)
```
Having the ability to bind the same texture to multiple texture units with different samplers is the key. It's used in some rendering techniques.

**Comment by cprogrammer1994** [comment]
I think the best would be to use samplers similar to vaos and textures similar to buffers.

Textures only hold data. Samplers hold texture references.

**Comment by einarf** [comment]
Got some simple code explaining what you mean here?

I assume you mean something like:
```py
texture = ctx.texture(...)
sampler = ctx.sampler(texture, *sampler_params)

# Will bind sampler and texture
sampler.bind(location=0)

# What happens with the previously bound sampler here? I'm guessing the binding clears?
texture.bind(location=1)
```

... so that a sampler will only affect the texture it references. When needing multiple ways to filter a texture we make multiple samplers referencing the same texture.

It means samplers are not really something you set on a texture channel. I guess this is actually more user friendly (and more performant reducing calls) and you don't end up with the awkward `Context.clear_samplers(..)`. In the vast majority of cases the samplers used during rendering will be more or less static, bit it could be a bit more cumbersome in certain instances as well.. but probably worth the sacrifice if it means using samplers is much more user friendly by not occupying the entire texture channel globally.

**Comment by cprogrammer1994** [comment]
Here is a simple example:

https://github.com/cprogrammer1994/ModernGL/blob/master/examples/experimental/crate.py#L58-L65

this example adds a sampler to a scope, but it could be bound manually with `sampler.use(location=0)`

**Comment by cprogrammer1994** [comment]
Here is the implementation of sampler.use:

https://github.com/cprogrammer1994/ModernGL/blob/501fa6421ff8d5b1c7485a87992764f53c897b63/moderngl/experimental/mgl/sampler.cpp#L41-L48

https://github.com/cprogrammer1994/ModernGL/blob/501fa6421ff8d5b1c7485a87992764f53c897b63/moderngl/experimental/mgl/context.cpp#L274-L282

**Comment by cprogrammer1994** [comment]
> What happens with the previously bound sampler here? I'm guessing the binding clears?

both the texture and the sampler on location=0 will be replaced with the new sampler and its texture

**Comment by einarf** [comment]
Looks great 👍 

Had to browse around looking at scope, contex and whatnot to see that whole picture. I really like how this all works together with the vao scope.

Close this issue I guess?
