### ISSUE TITLE
FYI: Broken project description on pypi

### ISSUE THREAD

**Issue by einarf** [cprogrammer1994/ModernGL#230]
https://pypi.org/project/ModernGL/5.4.0/

The 5.2.1 release looks fine: https://pypi.org/project/ModernGL/5.2.1/

I've had this problems with my own projects as well. It's usually because you are in an env with some older packages.

This is the required package versions.
```
setuptools>=38.6.0
wheel>=0.31.0
twine>=1.11.0
```

Usually it's the ``wheel`` package being outdated.

**Comment by cprogrammer1994** [comment]
I have seen this problem.

One must upload the source dist first otherwise this happens.

Thank you

**Comment by einarf** [comment]
I only release a single py3 ``whl`` for most of my projects and it works fine
