### ISSUE TITLE
ModernGL v5.4.1 on PyPI is broken

### ISSUE THREAD

**Issue by toaarnio** [cprogrammer1994/ModernGL#231]
`import moderngl` fails on version 5.4.1:

```
$ pip3 install --user moderngl
Collecting moderngl
  Using cached https://files.pythonhosted.org/packages/3f/de/5a6d42bd07e4e60d047ffafb70a724ec38c6e8d498ec70b1ea5213cc7523/moderngl-5.4.1-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: moderngl
Successfully installed moderngl-5.4.1
$
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import moderngl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/toaarnio/.local/lib/python3.5/site-packages/moderngl/__init__.py", line 13, in <module>
    from .compute_shader import *
  File "/home/toaarnio/.local/lib/python3.5/site-packages/moderngl/compute_shader.py", line 3, in <module>
    from .program_members import (Attribute, Subroutine, Uniform, UniformBlock,
ImportError: No module named 'moderngl.program_members'
>>> 
```

Version 5.3.0 works as expected.

**Comment by einarf** [comment]
Yup, you are right. It's broken because ``setup.py`` doesn't include ``moderngl.program_members`` I guess. The directory is not present in ``site-packages`` when installing it.

**Comment by einarf** [comment]
I made a fix #232 

When building source and bdist locally they files are copied in correctly.

**Comment by cprogrammer1994** [comment]
please don't close this until 5.4.2 is uploaded

**Comment by cprogrammer1994** [comment]
uploaded 5.4.2 please test
Thank you!

**Comment by einarf** [comment]
Seems to be working fine. I ran moderngl examples and my own examples at https://github.com/Contraz/demosys-py/tree/master/examples

All running perfectly.

**Comment by einarf** [comment]
I'll just mention this here as an observation:

Setuptools now have ``find_namespace_packages`` that is much more future proof with support for implicit namespace packages (without ``__init__py``)

This would then be a fairly future proof way to include packages:
```py
from setuptools import setup, find_namespace_packages

setup(
    packages=find_namespace_packages(include=['moderngl', 'modernl.*'])
)
```

**Comment by cprogrammer1994** [comment]
wow this looks a great solution
