### ISSUE TITLE
Any plans to support Direct State Access (DSA)?

### ISSUE THREAD

**Issue by jiawen** [cprogrammer1994/ModernGL#259]
OpenGL 4.5 adds direct state access, which makes wrappers like ModernGL much cleaner since most operations now no longer disturb context state (bind to create vs bind to modify vs bind to render).

Are there any plans to support GL 4.5 and DSA?

**Comment by einarf** [comment]
To have backwards compatibility to 3.3 or at least 4.1 is important for integrated graphics cards and the (shitty) fact that OS X stalled their OpenGL support at 4.1. It keeps the user base of this project fairly broad I imagine.

I do love the idea of using DSA and I'm not sure if we can easily have compatibility as well.
