### ISSUE TITLE
pip install fails on debian 9

### ISSUE THREAD

**Issue by jethornton** [cprogrammer1994/ModernGL#270]
**Description**

fails to install

**Proof of code**

pip install ModernGL
Collecting ModernGL
  Using cached https://files.pythonhosted.org/packages/5e/ac/fefe533ec3455f8b40a1c4e16371d88f1bbf899e7d53a82fc943d69e9731/moderngl-5.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lNBWi1/ModernGL/setup.py", line 17, in <module>
        raise Exception('Python 2 is not supported!')
    Exception: Python 2 is not supported!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lNBWi1/ModernGL/

```py



```

**Expected behavior**

pip to install moderngl

**Version info**

not installed yet

```



```

**Comment by einarf** [comment]
You are using python2 like the error message suggests I guess?

```
Exception: Python 2 is not supported!
```

**Comment by cprogrammer1994** [comment]
Use `pip3 install moderngl`

**Comment by jethornton** [comment]
einarf, I have both python 2 and python3 installed like most modern linux OS's

cprogrammer1994, you should update the install instructions

Thanks
JT

**Comment by einarf** [comment]
I'm guessing python2 is the default python in your linux distro.

Try:
```
python --version
python3 --version
```

Most people I know use pyenv to handle that.

**Comment by einarf** [comment]
Actually... ``README.md`` doesn't say much about python version. That can definitely be improved.

**Comment by KurtJacobson** [comment]
It took me quite a while to find that ModernGL was python3 only, as far as I can tell the only place this is mentioned explicitly is in the PyPi Classifiers. This info should be front and center.

Many modern linux distros ship with Py2 as the default (e.g. Mint 19.1, Ubuntu 18.04, Debian 9), so I would suggest that `pip3` be used for the install commands in the docs. It won't hurt if Py3 is the default, and with python "Explicit is better than implicit"!

**Comment by einarf** [comment]
Using `pip3` doesn't work well in all cases on all platforms though, but maybe it's a lesser evil making it easier for most people.

It means those who run pyenv or some other management tool for their python installs will by accident install the package in their system python version and not the one configured for the user/shell. This is not an issue when inside a virtualenv, so maybe just a minor thing.

**Comment by KurtJacobson** [comment]
> Using pip3 doesn't work well in all cases on all platforms

Neither does `pip`. At least `pip3` works in all (AFAIK) standard python installs, and my guess is there are a **lot** more people using those than pyenv or some other management tool...

**Comment by einarf** [comment]
Then all references to the `python` command must be replaced with `python3` as well, otherwise we are just moving the problem were users don't understand why `import moderngl` raises an `ImportError`.

This doesn't work with pyenv or virtualenvs, but maybe most people who use those are much more likely to identify what the issues is.

Maybe expanding the installation documentation (https://moderngl.readthedocs.io/en/stable/installation.html) is the way to go keeping `README.md` as is.

**Comment by cprogrammer1994** [comment]
> Maybe expanding the installation documentation (https://moderngl.readthedocs.io/en/stable/installation.html) is the way to go keeping README.md as is?

We can add a section for "older platforms"

We will keep `pip` in the `README.md`, by the way I always use `python -m pip` I don't expect any other programs beside the python executable to be on my path.

I was wondering if we should add something like `python_requires='>=3.5.0` to the `setup.py`.
Older pythons still could use old moderngl versions.
