### ISSUE TITLE
typo in code of pyglet window example?

### ISSUE THREAD

**Issue by tartley** [cprogrammer1994/ModernGL#282]
**Description**

I haven't run it, but on inspection of the pyglet window example, at this line:
https://github.com/cprogrammer1994/ModernGL/blob/master/examples/window/pyglet/window.py#L37

I think the assignment of `config.minor_version` contain a bug:

```py
config.major_version = self.gl_version[0]
config.minor_version = self.gl_version[0] # should be 1, not 0
```

Possibly undetected because the default glversion is `(3, 3)`

**Comment by einarf** [comment]
Wow. Thank you for pointing this out. Fixing right now.

**Comment by einarf** [comment]
Fixed. Merged. Close 😄

**Comment by cprogrammer1994** [comment]
Thank you for the bug report, and Thank you for the fix :)

**Comment by einarf** [comment]
This inspired #285 causing a lot of other fixes as well.
