### ISSUE TITLE
Default MSAA samples in example windows

### ISSUE THREAD

**Issue by einarf** [cprogrammer1994/ModernGL#284]
(Maybe not a bit deal, but might as well bring it up!)

I currently set 4 x MSAA as the default for the example windows but I don't know what kind of performance impact this will have for lower end or integrated graphics cards.

Should we maybe disable MSAA completely and instead let users specify that with the `--samples` parameter?

Pros: 
* Examples look beautiful by default

Cons: 
* Might affect performance for some
* Some examples may not want to use MSAA because it distorts the result

**Comment by cprogrammer1994** [comment]
I prefer samples=4 by default too. I have seen that samples=4 are working fine even in virtual machines with no extra gpu support, both windows and linux. I think we should keep 4 x MSAA by default.
