### ISSUE TITLE
Expose GL constants

### ISSUE THREAD

**Issue by martinbachtold** [cprogrammer1994/ModernGL#301]
Please expose OpenGL constants like GL_*.

PS: I're familiar in programing C/C++ and Python. Please give me advice to help you.

**Comment by einarf** [comment]
Some are available through flags: https://moderngl.readthedocs.io/en/stable/reference/context.html#moderngl.Context.enable_only (Still a couple more should probably also be exposed)

Any specific constant you are missing? The FAQ also mentions you can [use PyOpengGL to interact with ModernGL objects](https://github.com/cprogrammer1994/ModernGL#limitations-using-moderngl-over-pyopengl) is absolutely necessary.

The remaining constants and indirectly set and exposing them does not really help the user. I also come from C++ and it takes a bit to get used to the ModernGL approach.

5.x source : https://github.com/cprogrammer1994/ModernGL/tree/master/src
6.x source : https://github.com/cprogrammer1994/ModernGL/tree/master/moderngl/next/mgl

**Comment by einarf** [comment]
Closing this as it has been idle for a week. Be free to respond here if you have any more input on the issue.

**Comment by cprogrammer1994** [comment]
Just a quick note here:

ModernGL will not expose OpenGL constants. the constants exposed by ModernGL are not always the same as the ones exposed by OpenGL. A good example is enable flags... (enable flags can be combined in ModernGL, but not in OpenGL)
