### ISSUE TITLE
Idea: Discord server

### ISSUE THREAD

**Issue by einarf** [cprogrammer1994/ModernGL#302]
It seems a lot people have started using Discord as chat service to make a community for their users. This is fairly easy and low maintenance really. Anyone can ask or answer questions making all of this more into a community effort. Also being able to quickly share things like screenshots, documents and links make life a lot easier.

Also there are many practical integrations such as simple webhooks from github: https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

A vast amount of different bots as well.

If you think this is a good idea I can set up a server (if you havn't done it before).

**Comment by einarf** [comment]
I made a quick test server: https://discord.gg/W2Hkx8 (I ask for forgiveness!)

**Comment by cprogrammer1994** [comment]
Thank you for creating this :) can you also link it in the main readme?
