### ISSUE TITLE
MSAA without a window

### ISSUE THREAD

**Issue by M4gicT0** [cprogrammer1994/ModernGL#305]
Hi,

Is there a way to enable MSAA without a window ? I based my code on [Headless-rendering-with-python](https://github.com/cprogrammer1994/Headless-rendering-with-python ), but if I want to follow the OpenGL documentation, I have to create multisampled buffers and I don't know how to do that. I have very little knowledge of OpenGL and my use case is quite simple so if you could just point me in the right direction to enable anti-aliasing without a window that would be awesome.

Thanks for the good work!

**Comment by M4gicT0** [comment]
My bad ! I didn't read the example carefully.

**Comment by cprogrammer1994** [comment]
Just to repeat the key steps:

Create a fbo with samples=... (don't forget to create depth attachment if needed)
Create another fbo with samples=0
Run Context.copy_framebuffer(dst=second_fbo, src=first_fbo)
Read the second_fbo's content

**Comment by M4gicT0** [comment]
I tried that but it seems that the samples argument is only for `simple_framebuffer()` and not `framebuffer()` which allows for a depth attachment...
It seems to work with a `simple_framebuffer` though, so I don't know if I need the `depth_renderbuffer`.

**Comment by cprogrammer1994** [comment]
framebuffer(  color_attachments=[renderbuffer(samples=4)], depth_attachment(depth_renderbuffer(samples=4)  )

**Comment by M4gicT0** [comment]
Thank you so much!
