### ISSUE TITLE
Improve NewVertexArray

### ISSUE THREAD

**Issue by cprogrammer1994** [cprogrammer1994/ModernGL#42]
type and size checking
error checking

**Comment by stuaxo** [comment]
Can this take numpy arrays of floats ?

Would certainly be useful for interop, and can be useful for interop.

**Comment by cprogrammer1994** [comment]
```
# x, y,

1.0, 0.0,         
1.0, 0.0, 0.0,    

-0.5, 0.86,
0.0, 1.0, 0.0,

-0.5, -0.86,
0.0, 0.0, 1.0
```

**Comment by cprogrammer1994** [comment]
The `format` parameter is already useless since the dimension and type of the vertex attributes can be queried runtime.

I am not planning to remove it because:
- thrown errors are more programmer-friendly
- Later will have a support for padding `3f4x4f` (3 float, 4 bytes ignored, 4 floats)

_If there would be stronger cons I will definitely remove it._

**Comment by cprogrammer1994** [comment]
#65

**Comment by cprogrammer1994** [comment]
Solving #72 will fix the numpy related issue.
