### ISSUE TITLE
gl2ps backend ?

### ISSUE THREAD

**Issue by stuaxo** [cprogrammer1994/ModernGL#62]
Any chance of supporting gl2ps ?

VTK manages to use this to output to pdf and svg, it would be great if ModernGL could support this for the same reason.

**Comment by cprogrammer1994** [comment]
I will check out what is **gl2ps**

**Comment by cprogrammer1994** [comment]
```
Could not find a version that satisfies the requirement gl2ps
```

On PyPI:

Index of Packages Matching 'gl2ps'

There were no matches.

**Comment by cprogrammer1994** [comment]
```
gl2psBeginPage and gl2psEndPage                # must be ported
gl2psText and gl2psTextOpt                     # must be ported

gl2psDrawPixels                                # raster methods are deprecated
                                                 (must find an alternative)

gl2psSpecial                                   # not OpenGL dependent

gl2psEnable and gl2psDisable                   # implemented in ModernGL
gl2psPointSize and gl2psLineWidth              # implemented in ModernGL

gl2psBlendFunc                                 # implemented in ModernGL
                                                 (currently not customizable)

gl2psBeginViewport and gl2psEndViewport        # must be ported
gl2psSetOptions and gl2psGetOptions            # must be ported
```

**Comment by cprogrammer1994** [comment]
One can render to framebuffers with ModernGL, the content can be read and stored in some common image file formats with 1 - 5 lines of additional code to the rendering part. Pillow is capable of saving EPS files as well.

**Comment by stuaxo** [comment]
I think (though I might be wrong) that you get real vector output with gl2ps, whereas the frambuffer would be a bitmap.

**Comment by cprogrammer1994** [comment]
In this case, the only advantage of using modern OpenGL is to apply a projection and/or transformation to the vertices than save them to a file. The compute shader or Transform shader is capable of transforming  the vertices. Do the GL2PS able to convert the output of the fragment shader to vertex attributes (for example lighting aplied on a sphere).
I think the per vertex attribute can be calculated using normals and color values and texturing can be done as well fron vertex shader. The capability to read (transformed) vertex buffers will solve the problem partly. The newly created vertex attributes shall be converted to a format that PS can understand.

**Comment by stuaxo** [comment]
Yup, makes sense to close this for now,  - if I ever find out more I can try and revisit this with an actual patch :)
