### ISSUE TITLE
Python 2 build fails on linux.

### ISSUE THREAD

**Issue by cprogrammer1994** [cprogrammer1994/ModernGL#87]

**Comment by anvth** [comment]
Hey your suggestion did fix the error from Error.hpp file. However, there still two more errors:

> 
> 
> src/Program.cpp: In function ‘void MGLProgram_Invalidate(MGLProgram*)’:
> src/Program.cpp:375:11: error: ‘struct MGLProgram’ has no member named ‘ob_base’
>   program->ob_base.ob_type = &MGLInvalidObject_Type;
>            ^
> src/Program.cpp: In function ‘void MGLProgram_Compile(MGLProgram*, PyObject*)’:
> src/Program.cpp:413:69: error: ‘PyUnicode_AsUTF8’ was not declared in this scope
>      varyings_array[i] = PyUnicode_AsUTF8(PyList_GET_ITEM(outputs, i));
>                                                                      ^

**Comment by cprogrammer1994** [comment]
```
$ python2 -m ModernGL
('Vendor:', u'VMware, Inc.')
('Renderer:', u'Gallium 0.4 on SVGA3D; build: RELEASE;  LLVM;')
('Version:', u'3.3 (Core Profile) Mesa 12.0.6')
```

Compiles and runs.
**Tests are still failing**
