### ISSUE TITLE
A typo

### ISSUE THREAD

**Issue by xiongyaohua** [cprogrammer1994/ModernGL#97]
diff --git a/ModernGL/vertex_arrays.py b/ModernGL/vertex_arrays.py
index 91d1251..47890c0 100644
--- a/ModernGL/vertex_arrays.py
+++ b/ModernGL/vertex_arrays.py
@@ -161,7 +161,7 @@ class VertexArray:
         raise NotImplementedError()
 
     def __repr__(self):
-        return '<VertexArray: %d>' % self.glo
+        return '<VertexArray: %d>' % self.mglo
 
     @property
     def program(self) -> Program:

**Comment by cprogrammer1994** [comment]
what version do you use?
Paste the output of  `python -m ModernGL` here

**Comment by cprogrammer1994** [comment]
This is the correct code for `__repr__`:

```
return '<VertexArray: %d>' % self.glo
```

- The `self.mglo` is an object from the implementation (it is an **mgl** **o**bject)
- The `self.glo` is a property _(int)_ that returns `self.mglo.glo`

**Comment by cprogrammer1994** [comment]
Added a test, it is working fine in **4.1.7**
