### ISSUE TITLE
Support for 3D Textures?

### ISSUE THREAD

**Issue by ulricheck** [cprogrammer1994/ModernGL#98]
### Expected behavior

For rendering of (e.g. medical) volumes using raycasting, OpenGL provides 3D Textures and hardware accelerated tri-linear interpolation.

Do you plan to support 3D textures and if so how should they be implemented?

A clean implementation would probably require some changes in the base classes, 
since the for example the depth attribute for framebuffer attachments is already used for a different purpose.

### Actual behavior

3D Textures are not supported at the moment

### Solution 

I would be willing to contribute, however I'ld like to discuss a possible implementation first.

**Comment by cprogrammer1994** [comment]
> Do you plan to support 3D textures and if so how should they be implemented?

Yes, 3D Textures are welcome.

---

**Changes:**

1. Uniform getters and setters
2. A new type for the 3D textures in the c++ layer
3. **Probably** a new class for the 3D textures in the python layer
4. Framebuffer creation should support the new type
5. copy_framebuffer should support the new type
6. PBO pack/unpack should work fine with the new type

**Note:**

- Multisampled 3D textures can be implemented easily once 1.->6. is done.
- If step 3. is skipped then the Texture class in the python layer should have a `dimension` attribute.

**Investigation:**

The following questions apply to the OpenGL API.

- Can I create 3D **depth** textures?
- Can I attach a 3D texture to Framebuffer?
  - The entire texture?
  - Or partially?
  - How?
- Can I blit Framebuffers to 3D textures?
- What is the most common usage of 3D textures?

---

It would be great if you can link some examples of using 3D textures.

I am creating a new branch for this feature.

**Comment by cprogrammer1994** [comment]
[3d-textures branch](https://github.com/cprogrammer1994/ModernGL/tree/3d-textures) prepared.

1. [x] Uniform getters and setters

**Comment by ulricheck** [comment]
Thanks for the quick reply!!

My main use-case for 3D Textures is visualization of medical data, which typically comes in 3D voxel grids containing one Scalar value. A relatively simple (C++) example for such an application would look like: [GLSL Volume Rendering Example](https://github.com/toolchainX/Volume_Rendering_Using_GLSL/blob/master/main.cpp)

> Can I create 3D depth textures

What would such a structure represent? 
A depth texture is already "2.5D". 
In order to express surfaces using 3D volumes one typically uses (truncated) signed distance fields 

> Can I attach a 3D texture to Framebuffer?

I don't know - but have never seen such a thing

> Can I blit Framebuffers to 3D textures?

I don't know.

> What is the most common usage of 3D textures?

to represent discretised volumetric data .. e.g. CT/MRI/SPECT volumes for medical applications, volumetric vector fields for simulation, (truncated) signed distance fields for efficient collision detection when raycasting arbitrary (voxelized) geometries.

**Comment by cprogrammer1994** [comment]
Great then let's just implement 3D textures separately from the current texture implementation.

**Comment by cprogrammer1994** [comment]
I found the [answer](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_depth_texture.txt) for

> Can I create 3D depth textures?

**no**

3D texture - fbo interaction can be added later.

**Comment by cprogrammer1994** [comment]
I made [some changes](https://github.com/cprogrammer1994/ModernGL/compare/master...3d-textures), if you have time please test.
I did only implement the necessary functions to make [this example](https://github.com/cprogrammer1994/ModernGL/blob/3d-textures/examples/GLWindow/texture3D_example.py) working.

The example is meaningless it only proves that 3D textures are created correctly if you see red, green, and blue components as well.

- red is incremented along the x
- green is incremented along the y
- blue is incremented along the z

> (x, y, z) may be called (u, v, w) or (s, t, r)

![image](https://user-images.githubusercontent.com/11232402/27136601-064d2608-511c-11e7-9cc7-9693b48f92e0.png)

If you have time please take a look at the dummy methods I added and fix/implement them if necessary.
I will have time on Saturday to contribute to this.

**Comment by ulricheck** [comment]
hi Szabolcs,  

i'm on vacation until monday and will provide feedback next week.  

thanks for the super fast response!!  

cheers  
ulrich

**Comment by cprogrammer1994** [comment]
I will merge https://github.com/cprogrammer1994/ModernGL/pull/107 soon. Do you need anything from the TODO list?
I will make a release today that will contain these changes.

Feel free to post an example if you were able to use ModernGL and 3D Textures for "rendering of medical volumes".

**Please file an issue if you notice a strange behavior using the new features.**

**Comment by cprogrammer1994** [comment]
This example might not be the best but at least 3D textures are working fine:

![image](https://user-images.githubusercontent.com/11232402/27287771-112071c4-5505-11e7-8781-9ae986cd093b.png)

**Comment by Korijn** [comment]
Was just about to ask for this. Wicked! I will also share some findings later.  MedVis usecase here as well.

**Comment by cprogrammer1994** [comment]
closing, thanks for the issue!

**Comment by ulricheck** [comment]
Hi Szabolcs,

I’m currently working on a an example for Medical Volume Raycasting using the texture3D extension for ModernGL.
I’ll push it to GitHub and reference it here as soon as i have a minimally working example.

Thanks again for your quick fix!

best
Ulrich


On 30. June 2017 at 16:21:22, Szabolcs Dombi (notifications@github.com) wrote:

closing, thanks for the issue!

**Comment by cprogrammer1994** [comment]
Medical Volume Raycasting would be awesome thank you!
